//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.7.2558.0.
// 
namespace InformationInTransit.ProcessLogic {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AlphabetSequenceWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AlphabetSequenceWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloOperationCompleted;
        
        private System.Threading.SendOrPostCallback IDOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeEdOperationCompleted;
        
        private System.Threading.SendOrPostCallback IAmAfraidOfTheMarkOperationCompleted;
        
        private System.Threading.SendOrPostCallback InSuchOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeviticusAirDropOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwoFieldOperationCompleted;
        
        private System.Threading.SendOrPostCallback WhereAboutOfGodIsWhereAboutIKnowOperationCompleted;
        
        private System.Threading.SendOrPostCallback WhoSoughtTheEarlierPeopleTrialOperationCompleted;
        
        private System.Threading.SendOrPostCallback YourIDOrWhatDoYouWriteYourCommonIDOperationCompleted;
        
        /// <remarks/>
        public AlphabetSequenceWebService() {
            this.Url = "http://localhost/WordEngineering/WordUnion/AlphabetSequenceWebService.asmx";
        }
        
        /// <remarks/>
        public event HelloCompletedEventHandler HelloCompleted;
        
        /// <remarks/>
        public event IDCompletedEventHandler IDCompleted;
        
        /// <remarks/>
        public event DeEdCompletedEventHandler DeEdCompleted;
        
        /// <remarks/>
        public event IAmAfraidOfTheMarkCompletedEventHandler IAmAfraidOfTheMarkCompleted;
        
        /// <remarks/>
        public event InSuchCompletedEventHandler InSuchCompleted;
        
        /// <remarks/>
        public event LeviticusAirDropCompletedEventHandler LeviticusAirDropCompleted;
        
        /// <remarks/>
        public event QueryCompletedEventHandler QueryCompleted;
        
        /// <remarks/>
        public event TwoFieldCompletedEventHandler TwoFieldCompleted;
        
        /// <remarks/>
        public event WhereAboutOfGodIsWhereAboutIKnowCompletedEventHandler WhereAboutOfGodIsWhereAboutIKnowCompleted;
        
        /// <remarks/>
        public event WhoSoughtTheEarlierPeopleTrialCompletedEventHandler WhoSoughtTheEarlierPeopleTrialCompleted;
        
        /// <remarks/>
        public event YourIDOrWhatDoYouWriteYourCommonIDCompletedEventHandler YourIDOrWhatDoYouWriteYourCommonIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Hello", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Hello() {
            object[] results = this.Invoke("Hello", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHello(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Hello", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHello(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloAsync() {
            this.HelloAsync(null);
        }
        
        /// <remarks/>
        public void HelloAsync(object userState) {
            if ((this.HelloOperationCompleted == null)) {
                this.HelloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloOperationCompleted);
            }
            this.InvokeAsync("Hello", new object[0], this.HelloOperationCompleted, userState);
        }
        
        private void OnHelloOperationCompleted(object arg) {
            if ((this.HelloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloCompleted(this, new HelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ID(string word) {
            object[] results = this.Invoke("ID", new object[] {
                        word});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginID(string word, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ID", new object[] {
                        word}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void IDAsync(string word) {
            this.IDAsync(word, null);
        }
        
        /// <remarks/>
        public void IDAsync(string word, object userState) {
            if ((this.IDOperationCompleted == null)) {
                this.IDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIDOperationCompleted);
            }
            this.InvokeAsync("ID", new object[] {
                        word}, this.IDOperationCompleted, userState);
        }
        
        private void OnIDOperationCompleted(object arg) {
            if ((this.IDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IDCompleted(this, new IDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeEd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DeEd(decimal percent) {
            object[] results = this.Invoke("DeEd", new object[] {
                        percent});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDeEd(decimal percent, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DeEd", new object[] {
                        percent}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndDeEd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeEdAsync(decimal percent) {
            this.DeEdAsync(percent, null);
        }
        
        /// <remarks/>
        public void DeEdAsync(decimal percent, object userState) {
            if ((this.DeEdOperationCompleted == null)) {
                this.DeEdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeEdOperationCompleted);
            }
            this.InvokeAsync("DeEd", new object[] {
                        percent}, this.DeEdOperationCompleted, userState);
        }
        
        private void OnDeEdOperationCompleted(object arg) {
            if ((this.DeEdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeEdCompleted(this, new DeEdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAmAfraidOfTheMark", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IAmAfraidOfTheMark(string word, string scriptureReference) {
            object[] results = this.Invoke("IAmAfraidOfTheMark", new object[] {
                        word,
                        scriptureReference});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIAmAfraidOfTheMark(string word, string scriptureReference, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IAmAfraidOfTheMark", new object[] {
                        word,
                        scriptureReference}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndIAmAfraidOfTheMark(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IAmAfraidOfTheMarkAsync(string word, string scriptureReference) {
            this.IAmAfraidOfTheMarkAsync(word, scriptureReference, null);
        }
        
        /// <remarks/>
        public void IAmAfraidOfTheMarkAsync(string word, string scriptureReference, object userState) {
            if ((this.IAmAfraidOfTheMarkOperationCompleted == null)) {
                this.IAmAfraidOfTheMarkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIAmAfraidOfTheMarkOperationCompleted);
            }
            this.InvokeAsync("IAmAfraidOfTheMark", new object[] {
                        word,
                        scriptureReference}, this.IAmAfraidOfTheMarkOperationCompleted, userState);
        }
        
        private void OnIAmAfraidOfTheMarkOperationCompleted(object arg) {
            if ((this.IAmAfraidOfTheMarkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IAmAfraidOfTheMarkCompleted(this, new IAmAfraidOfTheMarkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InSuch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InSuch(string word, string booksCollection) {
            object[] results = this.Invoke("InSuch", new object[] {
                        word,
                        booksCollection});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInSuch(string word, string booksCollection, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InSuch", new object[] {
                        word,
                        booksCollection}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInSuch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InSuchAsync(string word, string booksCollection) {
            this.InSuchAsync(word, booksCollection, null);
        }
        
        /// <remarks/>
        public void InSuchAsync(string word, string booksCollection, object userState) {
            if ((this.InSuchOperationCompleted == null)) {
                this.InSuchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInSuchOperationCompleted);
            }
            this.InvokeAsync("InSuch", new object[] {
                        word,
                        booksCollection}, this.InSuchOperationCompleted, userState);
        }
        
        private void OnInSuchOperationCompleted(object arg) {
            if ((this.InSuchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InSuchCompleted(this, new InSuchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LeviticusAirDrop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LeviticusAirDrop(string word, string bookIDs) {
            object[] results = this.Invoke("LeviticusAirDrop", new object[] {
                        word,
                        bookIDs});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLeviticusAirDrop(string word, string bookIDs, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LeviticusAirDrop", new object[] {
                        word,
                        bookIDs}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndLeviticusAirDrop(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LeviticusAirDropAsync(string word, string bookIDs) {
            this.LeviticusAirDropAsync(word, bookIDs, null);
        }
        
        /// <remarks/>
        public void LeviticusAirDropAsync(string word, string bookIDs, object userState) {
            if ((this.LeviticusAirDropOperationCompleted == null)) {
                this.LeviticusAirDropOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeviticusAirDropOperationCompleted);
            }
            this.InvokeAsync("LeviticusAirDrop", new object[] {
                        word,
                        bookIDs}, this.LeviticusAirDropOperationCompleted, userState);
        }
        
        private void OnLeviticusAirDropOperationCompleted(object arg) {
            if ((this.LeviticusAirDropCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeviticusAirDropCompleted(this, new LeviticusAirDropCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Query", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Query(string word) {
            object[] results = this.Invoke("Query", new object[] {
                        word});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginQuery(string word, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Query", new object[] {
                        word}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndQuery(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryAsync(string word) {
            this.QueryAsync(word, null);
        }
        
        /// <remarks/>
        public void QueryAsync(string word, object userState) {
            if ((this.QueryOperationCompleted == null)) {
                this.QueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryOperationCompleted);
            }
            this.InvokeAsync("Query", new object[] {
                        word}, this.QueryOperationCompleted, userState);
        }
        
        private void OnQueryOperationCompleted(object arg) {
            if ((this.QueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryCompleted(this, new QueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwoField", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwoField(int bookID, int chapterID, int verseID, int increment, string choice) {
            object[] results = this.Invoke("TwoField", new object[] {
                        bookID,
                        chapterID,
                        verseID,
                        increment,
                        choice});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTwoField(int bookID, int chapterID, int verseID, int increment, string choice, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TwoField", new object[] {
                        bookID,
                        chapterID,
                        verseID,
                        increment,
                        choice}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndTwoField(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwoFieldAsync(int bookID, int chapterID, int verseID, int increment, string choice) {
            this.TwoFieldAsync(bookID, chapterID, verseID, increment, choice, null);
        }
        
        /// <remarks/>
        public void TwoFieldAsync(int bookID, int chapterID, int verseID, int increment, string choice, object userState) {
            if ((this.TwoFieldOperationCompleted == null)) {
                this.TwoFieldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwoFieldOperationCompleted);
            }
            this.InvokeAsync("TwoField", new object[] {
                        bookID,
                        chapterID,
                        verseID,
                        increment,
                        choice}, this.TwoFieldOperationCompleted, userState);
        }
        
        private void OnTwoFieldOperationCompleted(object arg) {
            if ((this.TwoFieldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwoFieldCompleted(this, new TwoFieldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WhereAboutOfGodIsWhereAboutIKnow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WhereAboutOfGodIsWhereAboutIKnow(string word) {
            object[] results = this.Invoke("WhereAboutOfGodIsWhereAboutIKnow", new object[] {
                        word});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWhereAboutOfGodIsWhereAboutIKnow(string word, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WhereAboutOfGodIsWhereAboutIKnow", new object[] {
                        word}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndWhereAboutOfGodIsWhereAboutIKnow(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WhereAboutOfGodIsWhereAboutIKnowAsync(string word) {
            this.WhereAboutOfGodIsWhereAboutIKnowAsync(word, null);
        }
        
        /// <remarks/>
        public void WhereAboutOfGodIsWhereAboutIKnowAsync(string word, object userState) {
            if ((this.WhereAboutOfGodIsWhereAboutIKnowOperationCompleted == null)) {
                this.WhereAboutOfGodIsWhereAboutIKnowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWhereAboutOfGodIsWhereAboutIKnowOperationCompleted);
            }
            this.InvokeAsync("WhereAboutOfGodIsWhereAboutIKnow", new object[] {
                        word}, this.WhereAboutOfGodIsWhereAboutIKnowOperationCompleted, userState);
        }
        
        private void OnWhereAboutOfGodIsWhereAboutIKnowOperationCompleted(object arg) {
            if ((this.WhereAboutOfGodIsWhereAboutIKnowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WhereAboutOfGodIsWhereAboutIKnowCompleted(this, new WhereAboutOfGodIsWhereAboutIKnowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WhoSoughtTheEarlierPeopleTrial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string WhoSoughtTheEarlierPeopleTrial(string word) {
            object[] results = this.Invoke("WhoSoughtTheEarlierPeopleTrial", new object[] {
                        word});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginWhoSoughtTheEarlierPeopleTrial(string word, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("WhoSoughtTheEarlierPeopleTrial", new object[] {
                        word}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndWhoSoughtTheEarlierPeopleTrial(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void WhoSoughtTheEarlierPeopleTrialAsync(string word) {
            this.WhoSoughtTheEarlierPeopleTrialAsync(word, null);
        }
        
        /// <remarks/>
        public void WhoSoughtTheEarlierPeopleTrialAsync(string word, object userState) {
            if ((this.WhoSoughtTheEarlierPeopleTrialOperationCompleted == null)) {
                this.WhoSoughtTheEarlierPeopleTrialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWhoSoughtTheEarlierPeopleTrialOperationCompleted);
            }
            this.InvokeAsync("WhoSoughtTheEarlierPeopleTrial", new object[] {
                        word}, this.WhoSoughtTheEarlierPeopleTrialOperationCompleted, userState);
        }
        
        private void OnWhoSoughtTheEarlierPeopleTrialOperationCompleted(object arg) {
            if ((this.WhoSoughtTheEarlierPeopleTrialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WhoSoughtTheEarlierPeopleTrialCompleted(this, new WhoSoughtTheEarlierPeopleTrialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/YourIDOrWhatDoYouWriteYourCommonID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YourIDOrWhatDoYouWriteYourCommonID(string scriptureReference, string scriptureSelection) {
            object[] results = this.Invoke("YourIDOrWhatDoYouWriteYourCommonID", new object[] {
                        scriptureReference,
                        scriptureSelection});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginYourIDOrWhatDoYouWriteYourCommonID(string scriptureReference, string scriptureSelection, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("YourIDOrWhatDoYouWriteYourCommonID", new object[] {
                        scriptureReference,
                        scriptureSelection}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndYourIDOrWhatDoYouWriteYourCommonID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YourIDOrWhatDoYouWriteYourCommonIDAsync(string scriptureReference, string scriptureSelection) {
            this.YourIDOrWhatDoYouWriteYourCommonIDAsync(scriptureReference, scriptureSelection, null);
        }
        
        /// <remarks/>
        public void YourIDOrWhatDoYouWriteYourCommonIDAsync(string scriptureReference, string scriptureSelection, object userState) {
            if ((this.YourIDOrWhatDoYouWriteYourCommonIDOperationCompleted == null)) {
                this.YourIDOrWhatDoYouWriteYourCommonIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYourIDOrWhatDoYouWriteYourCommonIDOperationCompleted);
            }
            this.InvokeAsync("YourIDOrWhatDoYouWriteYourCommonID", new object[] {
                        scriptureReference,
                        scriptureSelection}, this.YourIDOrWhatDoYouWriteYourCommonIDOperationCompleted, userState);
        }
        
        private void OnYourIDOrWhatDoYouWriteYourCommonIDOperationCompleted(object arg) {
            if ((this.YourIDOrWhatDoYouWriteYourCommonIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YourIDOrWhatDoYouWriteYourCommonIDCompleted(this, new YourIDOrWhatDoYouWriteYourCommonIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void HelloCompletedEventHandler(object sender, HelloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void IDCompletedEventHandler(object sender, IDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void DeEdCompletedEventHandler(object sender, DeEdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeEdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeEdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void IAmAfraidOfTheMarkCompletedEventHandler(object sender, IAmAfraidOfTheMarkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IAmAfraidOfTheMarkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IAmAfraidOfTheMarkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void InSuchCompletedEventHandler(object sender, InSuchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InSuchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InSuchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void LeviticusAirDropCompletedEventHandler(object sender, LeviticusAirDropCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeviticusAirDropCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeviticusAirDropCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void QueryCompletedEventHandler(object sender, QueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void TwoFieldCompletedEventHandler(object sender, TwoFieldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwoFieldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwoFieldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void WhereAboutOfGodIsWhereAboutIKnowCompletedEventHandler(object sender, WhereAboutOfGodIsWhereAboutIKnowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WhereAboutOfGodIsWhereAboutIKnowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WhereAboutOfGodIsWhereAboutIKnowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void WhoSoughtTheEarlierPeopleTrialCompletedEventHandler(object sender, WhoSoughtTheEarlierPeopleTrialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WhoSoughtTheEarlierPeopleTrialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WhoSoughtTheEarlierPeopleTrialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void YourIDOrWhatDoYouWriteYourCommonIDCompletedEventHandler(object sender, YourIDOrWhatDoYouWriteYourCommonIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YourIDOrWhatDoYouWriteYourCommonIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YourIDOrWhatDoYouWriteYourCommonIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
