@ECHO OFF
REM Created.	2016-01-20.
REM csc /main:InformationInTransit.ProcessLogic.UsingUserDatagramProtocolUDPServicesClient UsingUserDatagramProtocolUDPServicesClient.cs IPClassSubnetMask.cs IPClassBroadcastAddress.cs
csc /main:InformationInTransit.ProcessLogic.UsingUserDatagramProtocolUDPServicesClient UsingUserDatagramProtocolUDPServicesClient.cs IPAddressHelper.cs
