        git add      2020-12-09T1528gitadd.cmd
        git add      2020-12-09T1528gitaddArchive.cmd
        git add      2020-12-09T1716gitadd.cmd
        git add      2020-12-09T1716gitaddArchive.cmd
        git add      IIS/WordEngineering/IronPython.py
        git add      IIS/WordEngineering/MvcApplicationRazor.sln
        git add      IIS/WordEngineering/NumberConverter.aspx
        git add      IIS/WordEngineering/NumberConverter.aspx.cs
        git add      IIS/WordEngineering/OpenSearch.html
        git add      IIS/WordEngineering/OpenSearch.xml
        git add      IIS/WordEngineering/OurNumbers.html
        git add      IIS/WordEngineering/RSSReader.aspx
        git add      IIS/WordEngineering/RSSReader.aspx.cs
        git add      IIS/WordEngineering/ReadMe.txt
        git add      IIS/WordEngineering/ReleaseNotes.txt
        git add      IIS/WordEngineering/RomanNumeralConverter.html
        git add      IIS/WordEngineering/Site.Master.cs
        git add      IIS/WordEngineering/Site.Master.designer.cs
        git add      IIS/WordEngineering/Site.Master2019-10-13T0516
        git add      IIS/WordEngineering/StudentClass.aspx
        git add      IIS/WordEngineering/StudentClass.aspx.cs
        git add      IIS/WordEngineering/TaniaRascia.com_-_Ghibli.html
        git add      IIS/WordEngineering/TaniaRascia.com_-_GhibliArchive.html
        git add      IIS/WordEngineering/Text-to-speech.aspx
        git add      IIS/WordEngineering/Text-to-speech.aspx.cs
        git add      IIS/WordEngineering/UpgradeLog.XML
        git add      IIS/WordEngineering/UpgradeLog.htm
        git add      IIS/WordEngineering/WeatherForecast.aspx
        git add      IIS/WordEngineering/WeatherForecast.aspx.cs
        git add      IIS/WordEngineering/WeatherForecast.aspx.designer.cs
        git add      IIS/WordEngineering/Web.Debug.config
        git add      IIS/WordEngineering/Web.Release.config
        git add      IIS/WordEngineering/Web.config
        git add      IIS/WordEngineering/Web.config.20170101
        git add      IIS/WordEngineering/Web.config20120920
        git add      IIS/WordEngineering/Web.configRelease2018-02-09T1902
        git add      IIS/WordEngineering/Web.configRelease2018-10-25T1745
        git add      IIS/WordEngineering/Web.configRelease2018-10-25T1750
        git add      IIS/WordEngineering/Web.configRelease2019-09-24
        git add      IIS/WordEngineering/Web.configRelease2019-09-24T2222
        git add      IIS/WordEngineering/Web2013-10-29T1300.config
        git add      IIS/WordEngineering/Web2017-11-01T2055.config
        git add      IIS/WordEngineering/Web2017-11-01T2134.config
        git add      IIS/WordEngineering/Web2019-02-13T2049.config
        git add      IIS/WordEngineering/Web2019-02-13T2217.config
        git add      IIS/WordEngineering/WebArchive.config
        git add      IIS/WordEngineering/WebRelease2014-08-19T2115.config
        git add      IIS/WordEngineering/WebRelease2018-06-08T1700.config
        git add      IIS/WordEngineering/Web__20131019.config
        git add      IIS/WordEngineering/WordEngineering.csproj
        git add      IIS/WordEngineering/WordEngineering.csproj.user
        git add      IIS/WordEngineering/WordEngineering.sln
        git add      IIS/WordEngineering/WordGroup/DistributedLedgerAlsoCalledASharedLedgerOrDistributedLedgerTechnologyOrDLT.asmx
        git add      IIS/WordEngineering/WordGroup/DistributedLedgerAlsoCalledASharedLedgerOrDistributedLedgerTechnologyOrDLT.html
        git add      IIS/WordEngineering/WordGroup/DistributedLedgerAlsoCalledASharedLedgerOrDistributedLedgerTechnologyOrDLTArchive.asmx
        git add      IIS/WordEngineering/WordGroup/DistributedLedgerAlsoCalledASharedLedgerOrDistributedLedgerTechnologyOrDLTArchive.html
        git add      IIS/WordEngineering/WordGroup/WantingMeToTheGrooveButTheGrooveDontTakeControlOfMeWantingMeToControlOfMyself.asmx
        git add      IIS/WordEngineering/WordGroup/WantingMeToTheGrooveButTheGrooveDontTakeControlOfMeWantingMeToControlOfMyself.html
        git add      IIS/WordEngineering/WordGroup/WantingMeToTheGrooveButTheGrooveDontTakeControlOfMeWantingMeToControlOfMyselfArchive.asmx
        git add      IIS/WordEngineering/WordGroup/WantingMeToTheGrooveButTheGrooveDontTakeControlOfMeWantingMeToControlOfMyselfArchive.html
        git add      IIS/WordEngineering/WordGroup/WhatDivideTheConcern.html
        git add      IIS/WordEngineering/WordGroup/WhatDivideTheConcernArchive.html
        git add      IIS/WordEngineering/WordGroup/WhatHisWordCanSayByDeedAlone.asmx
        git add      IIS/WordEngineering/WordGroup/WhatHisWordCanSayByDeedAlone.html
        git add      IIS/WordEngineering/WordGroup/WhatHisWordCanSayByDeedAloneArchive.asmx
        git add      IIS/WordEngineering/WordGroup/WhatHisWordCanSayByDeedAloneArchive.html
        git add      IIS/WordEngineering/WordGroup/WhatKindOfPlacesDoYouGuysLikeGoingTo.html
        git add      IIS/WordEngineering/WordGroup/WhatKindOfPlacesDoYouGuysLikeGoingToArchive.html
        git add      IIS/WordEngineering/WordGroup/WhatKindOfPlacesDoYouGuysLikeGoingToRelease2020-11-03T1320.html
        git add      IIS/WordEngineering/WordGroup/WhatRolesAreMentionMostInTheBible.Archiveasmx
        git add      IIS/WordEngineering/WordGroup/WhatRolesAreMentionMostInTheBible.asmx
        git add      IIS/WordEngineering/WordGroup/WhatRolesAreMentionMostInTheBible.html
        git add      IIS/WordEngineering/WordGroup/WhatRolesAreMentionMostInTheBibleArchive.html
        git add      IIS/WordEngineering/WordGroup/WhatSetsUsApartIsHowWeAreFavorableAtUse.asmx
        git add      IIS/WordEngineering/WordGroup/WhatSetsUsApartIsHowWeAreFavorableAtUse.html
        git add      IIS/WordEngineering/WordGroup/WhatSetsUsApartIsHowWeAreFavorableAtUseArchive.asmx
        git add      IIS/WordEngineering/WordGroup/WhatSetsUsApartIsHowWeAreFavorableAtUseArchive.html
        git add      IIS/WordEngineering/WordGroup/WhatTimeIsItPleaseNineFortyNine.html
        git add      IIS/WordEngineering/WordGroup/WhatTimeIsItPleaseNineFortyNineArchive.html
        git add      IIS/WordEngineering/WordGroup/WhenDoWeDwarfOurPrivilege.asmx
        git add      IIS/WordEngineering/WordGroup/WhenDoWeDwarfOurPrivilege.html
        git add      IIS/WordEngineering/WordGroup/WhenDoWeDwarfOurPrivilegeArchive.asmx
        git add      IIS/WordEngineering/WordGroup/WhenDoWeDwarfOurPrivilegeArchive.html
        git add      IIS/WordEngineering/WordGroup/WhenEmptynessIsFarAway.asmx
        git add      IIS/WordEngineering/WordGroup/WhenEmptynessIsFarAway.html
        git add      IIS/WordEngineering/WordGroup/WhenEmptynessIsFarAwayArchive.asmx
        git add      IIS/WordEngineering/WordGroup/WhenEmptynessIsFarAwayArchive.html
        git add      IIS/WordEngineering/WordGroup/WhenNothingUpToDateIsFurtherMore.asmx
        git add      IIS/WordEngineering/WordGroup/WhenNothingUpToDateIsFurtherMore.html
        git add      IIS/WordEngineering/WordGroup/WhenNothingUpToDateIsFurtherMoreArchive.asmx
        git add      IIS/WordEngineering/WordGroup/WhenNothingUpToDateIsFurtherMoreArchive.html
        git add      IIS/WordEngineering/WordGroup/WhenOneSeldomlyDoWhatIsRightOneSeldomlyDoWhatIsMeans.html
        git add      IIS/WordEngineering/WordGroup/WhenOneSeldomlyDoWhatIsRightOneSeldomlyDoWhatIsMeansArchive.html
        git add      IIS/WordEngineering/WordGroup/WhenOneSeldomlyDoWhatIsRightOneSeldomlyDoWhatIsMeansRelease2019-01-10T1900.html
        git add      IIS/WordEngineering/WordGroup/WhenThePastorIsPreachingYouDontWithTheScriptureToComeInSubsequent.asmx
        git add      IIS/WordEngineering/WordGroup/WhenThePastorIsPreachingYouDontWithTheScriptureToComeInSubsequent.html
        git add      IIS/WordEngineering/WordGroup/WhenThePastorIsPreachingYouDontWithTheScriptureToComeInSubsequentArchive.asmx
        git add      IIS/WordEngineering/WordGroup/WhenThePastorIsPreachingYouDontWithTheScriptureToComeInSubsequentArchive.html
        git add      IIS/WordEngineering/WordGroup/WhereYouWillLiveForeverThatIsWhatIHaveChosenForYou.html
        git add      IIS/WordEngineering/WordGroup/WhereYouWillLiveForeverThatIsWhatIHaveChosenForYouArchive.html
        git add      IIS/WordEngineering/WordGroup/WhichBookMentionsNumberTheMost.asmx
        git add      IIS/WordEngineering/WordGroup/WhichBookMentionsNumberTheMost.html
        git add      IIS/WordEngineering/WordGroup/WhichBookMentionsNumberTheMostArchive.asmx
        git add      IIS/WordEngineering/WordGroup/WhichBookMentionsNumberTheMostArchive.html
        git add      IIS/WordEngineering/WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGood.asmx
        git add      IIS/WordEngineering/WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGood.html
        git add      IIS/WordEngineering/WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGoodArchive.asmx
        git add      IIS/WordEngineering/WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGoodArchive.html
        git add      IIS/WordEngineering/WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGoodRelease2019-12-22T1501.asmx
        git add      IIS/WordEngineering/WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGoodRelease2019-12-22T1501.html
        git add      IIS/WordEngineering/WordGroup/WordOccurrences.asmx
        git add      IIS/WordEngineering/WordGroup/WordOccurrences.html
        git add      IIS/WordEngineering/WordGroup/WordOccurrencesArchive.asmx
        git add      IIS/WordEngineering/WordGroup/WordOccurrencesArchive.html
        git add      IIS/WordEngineering/WordGroup/WordOccurrencesRelease2020-01-09T1922.asmx
        git add      IIS/WordEngineering/WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMoving.asmx
        git add      IIS/WordEngineering/WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMoving.html
        git add      IIS/WordEngineering/WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMovingArchive.asmx
        git add      IIS/WordEngineering/WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMovingArchive.html
        git add      IIS/WordEngineering/WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMovingRelease2019-12-09T1742.asmx
        git add      IIS/WordEngineering/WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMovingRelease2019-12-09T1900.html
        git add      IIS/WordEngineering/WordGroup/YouDontNeedAHornet.asmx
        git add      IIS/WordEngineering/WordGroup/YouDontNeedAHornet.html
        git add      IIS/WordEngineering/WordGroup/YouDontNeedAHornetArchive.asmx
        git add      IIS/WordEngineering/WordGroup/YouDontNeedAHornetArchive.html
        git add      IIS/WordEngineering/WordGroup/YouJustFakeOneTakeOne.asmx
        git add      IIS/WordEngineering/WordGroup/YouJustFakeOneTakeOne.html
        git add      IIS/WordEngineering/WordGroup/YouJustFakeOneTakeOneArchive.asmx
        git add      IIS/WordEngineering/WordGroup/YouJustFakeOneTakeOneArchive.html
        git add      IIS/WordEngineering/WordGroup/YourPartOfTheHistory.asmx
        git add      IIS/WordEngineering/WordGroup/YourPartOfTheHistory.html
        git add      IIS/WordEngineering/WordGroup/YourPartOfTheHistoryArchive.asmx
        git add      IIS/WordEngineering/WordGroup/YourPartOfTheHistoryArchive.html
        git add      IIS/WordEngineering/WordGroup/YourPartOfTheHistoryRelease2019-12-18T0130.html
        git add      IIS/WordEngineering/WordGroup/YourPartOfTheHistoryRelease2019-12-18T0140.asmx
        git add      IIS/WordEngineering/WordUnion/EqualAsPeopleWebService.asmx
        git add      IIS/WordEngineering/WordUnion/EqualSide.asmx
        git add      IIS/WordEngineering/WordUnion/ExplainPaulsGospel.asmx
        git add      IIS/WordEngineering/WordUnion/FatherSide.asmx
        git add      IIS/WordEngineering/WordUnion/FindTheWordThatMakesThePercentageOfTheWord.asmx
        git add      IIS/WordEngineering/WordUnion/Full-TextSearch.asmx
        git add      IIS/WordEngineering/WordUnion/Full-TextSearchHisWord.asmx
        git add      IIS/WordEngineering/WordUnion/Full-TextSearchRelease2018-05-20.asmx
        git add      IIS/WordEngineering/WordUnion/Full-TextSearchRelease2018-05-20T0800.asmx
        git add      IIS/WordEngineering/WordUnion/FullPositionWebService.asmx
        git add      IIS/WordEngineering/WordUnion/GodTitle.asmx
        git add      IIS/WordEngineering/WordUnion/GreekWebService.asmx
        git add      IIS/WordEngineering/WordUnion/HeActedHisWillOut.asmx
        git add      IIS/WordEngineering/WordUnion/HeActedHisWillOutArchive.asmx
        git add      IIS/WordEngineering/WordUnion/HeFinallyShowedItToMe.asmx
        git add      IIS/WordEngineering/WordUnion/HeIsHalfGone.asmx
        git add      IIS/WordEngineering/WordUnion/HisWord.asmx
        git add      IIS/WordEngineering/WordUnion/HobiGoUp.asmx
        git add      IIS/WordEngineering/WordUnion/HowWeWouldLearnToSay.asmx
        git add      IIS/WordEngineering/WordUnion/IAmNotForgotten.asmx
        git add      IIS/WordEngineering/WordUnion/IAmTotallyInterestedInAForeignKey.asmx
        git add      IIS/WordEngineering/WordUnion/IHaveKnowItForTwentySix.asmx
        git add      IIS/WordEngineering/WordUnion/IRealizeMyFullSenseInMakingMan.asmx
        git add      IIS/WordEngineering/WordUnion/IThinkInAfricaWaterDryRelease2018-05-20T1800.asmx
        git add      IIS/WordEngineering/WordUnion/InDefine.asmx
        git add      IIS/WordEngineering/WordUnion/IsMakingRemainderOfTime.asmx
        git add      IIS/WordEngineering/WordUnion/JeshuaBrothers.asmx
        git add      IIS/WordEngineering/WordUnion/LastAfter.asmx
        git add      IIS/WordEngineering/WordUnion/LifesNormancy.asmx
        git add      IIS/WordEngineering/WordUnion/LovingLiving.asmx
        git add      IIS/WordEngineering/WordUnion/MakingTodayAMemoryOfTomorrow.asmx
        git add      IIS/WordEngineering/WordUnion/MapTime.asmx
        git add      IIS/WordEngineering/WordUnion/MeISupposeInTime.asmx
        git add      IIS/WordEngineering/WordUnion/MyCondemn.asmx
        git add      IIS/WordEngineering/WordUnion/NaturalOccurringSequenceWebService.asmx
        git add      IIS/WordEngineering/WordUnion/NothingBeyondMeIsAcceptableToMe.asmx
        git add      IIS/WordEngineering/WordUnion/NumberSignWebService.asmx
        git add      IIS/WordEngineering/WordUnion/OftenTimeIsTheGuise.asmx
        git add      IIS/WordEngineering/WordUnion/OneForTheForbiddenBoy.asmx
        git add      IIS/WordEngineering/WordUnion/OneOfTheFamousWebsiteIKnowThrewUsByComfortAsYouGoTo.asmx
        git add      IIS/WordEngineering/WordUnion/OurPeople.asmx
        git add      IIS/WordEngineering/WordUnion/OurPeopleArchive.asmx
        git add      IIS/WordEngineering/WordUnion/OurTypeAtTheEnd.asmx
        git add      IIS/WordEngineering/WordUnion/People.asmx
        git add      IIS/WordEngineering/WordUnion/PhraseTwoOrMoreWordsThatReOccur.asmx
        git add      IIS/WordEngineering/WordUnion/RepeatedWords.asmx
        git add      IIS/WordEngineering/WordUnion/SQLServerManagementObjectsSMO.asmx
        git add      IIS/WordEngineering/WordUnion/SQLServerManagementObjectsSMOArchive.asmx
        git add      IIS/WordEngineering/WordUnion/SQLServerManagementObjectsSMORelease2019-09-27.asmx
        git add      IIS/WordEngineering/WordUnion/SQLToHTMLTable.asmx
        git add      IIS/WordEngineering/WordUnion/SchemaWebService.asmx
        git add      IIS/WordEngineering/WordUnion/ScriptureReferenceWebServiceRelease2018-05-19T1900.asmx
        git add      IIS/WordEngineering/WordUnion/ScriptureReferenceWebServiceRelease2018-05-19T1915.asmx
        git add      IIS/WordEngineering/WordUnion/ShowingAPersonHowHeIsTrulyIs.asmx
        git add      IIS/WordEngineering/WordUnion/StatedInTheBible.asmx
        git add      IIS/WordEngineering/WordUnion/StatedInTheBibleArchive.asmx
        git add      IIS/WordEngineering/WordUnion/SternIsTheBloodyNameOfTheSin.asmx
        git add      IIS/WordEngineering/WordUnion/SysColumns.asmx
        git add      IIS/WordEngineering/WordUnion/TheLastTimeArchive.asmx
        git add      IIS/WordEngineering/WordUnion/TheTripAmong.asmx
        git add      IIS/WordEngineering/WordUnion/TheTripAmongArchive.asmx
        git add      IIS/WordEngineering/WordUnion/ThinkLikeIThinkYouWouldThink.asmx
        git add      IIS/WordEngineering/WordUnion/ThisPaperWillArgueTheSumOfCost.asmx
        git add      IIS/WordEngineering/WordUnion/ToACertainDegreeLetManSeemHimself.asmx
        git add      IIS/WordEngineering/WordUnion/ToBeginAtTheLeastIsToSeeTheResemblance.asmx
        git add      IIS/WordEngineering/WordUnion/ToHaveLiveALifeIAmAProveOf.asmx
        git add      IIS/WordEngineering/WordUnion/ToHaveLiveALifeIAmAProveOfRelease2018-04-23T2130.asmx
        git add      IIS/WordEngineering/WordUnion/ToHaveLiveALifeIAmAProveOfRelease2018-04-23T2145.asmx
        git add      IIS/WordEngineering/WordUnion/ToHaveLiveALifeIAmAProveOfRelease2018-04-24T0400.asmx
        git add      IIS/WordEngineering/WordUnion/ToHaveLiveALifeIAmAProveOfRelease2018-04-24T0800.asmx
        git add      IIS/WordEngineering/WordUnion/ToKnowMyPercentageOfMyScore.asmx
        git add      IIS/WordEngineering/WordUnion/ToLiveACompleteLifeIsNotToHaveSpentTheFewWebService.asmx
        git add      IIS/WordEngineering/WordUnion/ToRememberHisConversationAsMine.asmx
        git add      IIS/WordEngineering/WordUnion/ToRememberHisConversationAsMineArchive.asmx
        git add      IIS/WordEngineering/WordUnion/TypesTheBeing.asmx
        git add      IIS/WordEngineering/WordUnion/UserTechnologyWebService.asmx
        git add      IIS/WordEngineering/WordUnion/WhatAreTheRegularFactorInfluencingYourPerception.asmx
        git add      IIS/WordEngineering/WordUnion/WhatIsAcceptedAsAPersonIsAcceptedAsAGod.asmx
        git add      IIS/WordEngineering/WordUnion/WhatIsYourQuestOfInterestCommonGoalsWebService.asmx
        git add      IIS/WordEngineering/WordUnion/WhenIsFinallyFirst.asmx
        git add      IIS/WordEngineering/WordUnion/WhenIsHeLivingAsAFutureOfOurBeing.asmx
        git add      IIS/WordEngineering/WordUnion/WhenLifeChooseAPathLifeIsMadeOfAPart.asmx
        git add      IIS/WordEngineering/WordUnion/WithEveryDifferingToYourAdvantage.asmx
        git add      IIS/WordEngineering/WordUnion/WordMeaning.asmx
        git add      IIS/WordEngineering/WordUnion/WordToNumberWebService.asmx
        git add      IIS/WordEngineering/WordUnion/WorldRound.asmx
        git add      IIS/WordEngineering/WordUnion/YouCannotComeToMeUnlessYouAreSelfAloneWebService.asmx
        git add      IIS/WordEngineering/WordUnion/YouCantGoogleItOnFriday.asmx
        git add      IIS/WordEngineering/WordUnion/YouCantGoogleItOnFridayRelease2018-06-25T1612.asmx
        git add      IIS/WordEngineering/WordUnion/YouHaveIncludedInYouWebService.asmx
        git add      IIS/WordEngineering/XmlToJson.aspx
        git add      IIS/WordEngineering/jqx_index.htm
        git add      IIS/WordEngineering/json.ip.html
        git add      IIS/WordEngineering/reCaptcha.aspx
        git add      IIS/WordEngineering/reCaptcha.aspx.cs
        git add      IIS/WordEngineering/robots.txt
        git add      gitCommand2020-12-09T1518.bat
        git add      gitCommand2020-12-09T1518Archive.bat
        git add      gitadd.cmd
        git add      issues/gitPush_01_20201209_0304pm.txt
        git add      issues/gitPush_01_20201209_0311pm.txt

        git add      Batch/2017-01-02DoingSomething.bat
        git add      Batch/2017-01-02DoingSomethingArchive.bat
        git add      Google/Go/SqlServerSample/go-mssqldb/go.sum
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/ie.css
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/plugins/buttons/readme.txt
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/plugins/buttons/screen.css
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/plugins/fancy-type/readme.txt
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/plugins/link-icons/readme.txt
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/plugins/link-icons/screen.css
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/plugins/rtl/readme.txt
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/plugins/rtl/screen.css
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/print.css
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/screen.css
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/src/forms.css
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/src/grid.css
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/src/ie.css
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/src/print.css
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/src/reset.css
        git add      IIS/WordEngineering/CascadingStyleSheet/BluePrintCss.org/blueprint/src/typography.css
        git add      IIS/WordEngineering/CascadingStyleSheet/MeyerWeb.com/reset.css
        git add      IIS/WordEngineering/CascadingStyleSheet/My first styled page.html
        git add      IIS/WordEngineering/CascadingStyleSheet/PeterGasston/Chunkfive-webfont.svg
        git add      IIS/WordEngineering/ChristianHeilmann.com/SongSearch/README.md
        git add      IIS/WordEngineering/ChristianHeilmann.com/SongSearch/index.html
        git add      IIS/WordEngineering/ChristianHeilmann.com/SongSearch/manifest.json
        git add      IIS/WordEngineering/ChristianHeilmann.com/SongSearch/songsearch-sw.js
        git add      IIS/WordEngineering/ChristianHeilmann.com/SongSearch/songsearch.css
        git add      IIS/WordEngineering/ChristianHeilmann.com/SongSearch/songsearch.js
        git add      IIS/WordEngineering/ChristianHeilmann.com/SongSearch/songsearchworker.js
        git add      IIS/WordEngineering/GeoLocation/NoMe.js.com/nome-0.1.9.js
        git add      IIS/WordEngineering/GeoLocation/yqlgeo.js
        git add      IIS/WordEngineering/IgnitersWorld.com/jsonQ.min.js
        git add      IIS/WordEngineering/JavaScript/Canvas/O'Reilly Canvas/Chapter01/O'Reilly Canvas Chapter 01 Exercise 04.html
        git add      IIS/WordEngineering/JavaScript/Canvas/learnjs.io/glitch-canvas.js.sql
        git add      IIS/WordEngineering/JavaScript/Canvas/learnjs.io/glitch-canvas.min.js.sql
        git add      IIS/WordEngineering/Mozilla/PDF.js/pdf.js
        git add      IIS/WordEngineering/Mozilla/PDF.js/pdf.js_-_HelloWorld.pdf
        git add      IIS/WordEngineering/Mozilla/PDF.js/pdf.worker.js
        git add      IIS/WordEngineering/MySQL/2020-09-03T1442MySQL_DatabaseBible_TableBibleBook.sql
        git add      IIS/WordEngineering/MySQL/2020-09-03T1442MySQL_DatabaseBible_TableBibleBookArchive.sql
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/Scripts/jquery-1.7.1.js
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/Scripts/jquery-1.7.1.min.js
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/Web.config
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/css/basic.css
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/css/basic_ie.css
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/css/bootstrap-theme.css
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/css/bootstrap-theme.min.css
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/css/bootstrap.css
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/css/bootstrap.min.css
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/fonts/glyphicons-halflings-regular.svg
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/js/bootstrap.js
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/js/bootstrap.min.js
        git add      IIS/WordEngineering/OmarAlZabir/SQLServerDashboard/js/jquery.flot.time.min.js
        git add      IIS/WordEngineering/RatingRank/Python/statistics.py
        git add      IIS/WordEngineering/Resume/debug.log
        git add      IIS/WordEngineering/Scripts/jquery-1.7.1.js
        git add      IIS/WordEngineering/Scripts/jquery-1.7.1.min.js
        git add      IIS/WordEngineering/Scripts/json2.js
        git add      IIS/WordEngineering/Styles/qunit-git.css
        git add      IIS/WordEngineering/TextBelt/daluu/textbelt-clients/web/helloworld.pdf
        git add      IIS/WordEngineering/WebAssembly/html_template/shell_minimal.html
        git add      IIS/WordEngineering/WordGroup/DistributedLedgerAlsoCalledASharedLedgerOrDistributedLedgerTechnologyOrDLT.html
        git add      IIS/WordEngineering/WordGroup/DistributedLedgerAlsoCalledASharedLedgerOrDistributedLedgerTechnologyOrDLTArchive.html
        git add      IIS/WordEngineering/jstree.com/dist/jstree.js
        git add      IIS/WordEngineering/jstree.com/dist/jstree.min.js
        git add      IIS/WordEngineering/jstree.com/dist/themes/default-dark/style.css
        git add      IIS/WordEngineering/jstree.com/dist/themes/default/style.css
        git add      IIS/WordEngineering/nytimes.com/nytimes.css
        git add      IIS/WordEngineering/nytimes.com/nytimes_start.html
        git add      IIS/WordEngineering/nytimes.com/nytimes_startRelease2018-01-30T2000.html
        git add      IIS/WordEngineering/nytimes.com/nytimes_startRelease2018-01-30T2020.html
        git add      InformationInTransit/InformationInTransit.dll
        git add      InformationInTransit/ProcessLogic/QRCoder.cs
        git add      InformationInTransit/ProcessLogic/iata-airport-codes/airport-codes.sql
        git add      cpp/Stroustrup.com/std_lib_facilities.h
        git add      gitCommand2020-12-09T1518Archive.bat

        git add      2020-12-09T1931gitadd.cmd
        git add		 2020-12-09T1931gitaddArchive.cmd
        git add        2020-12-10T1622gitadd.cmd
        git add        2020-12-10T1622gitaddArchive.cmd
