git add        ../../2020-12-09T1716gitadd.cmd
git add        ../../2020-12-09T1716gitaddArchive.cmd
git add        National Oceanic and Atmospheric Administration (NOAA).sln
git add        Text-to-speech Release2015-08-08T1830.aspx.cs
git add        Twitter API Tutorial.sln
git add        Web Release2015-08-06T0604.config
git add        Web Release2015-08-08T1830.config
git add        Web Release2018-02-09T1856.config
git add        WordUnion/EqualAsPeopleWebService.asmx
git add        WordUnion/EqualSide.asmx
git add        WordUnion/ExplainPaulsGospel.asmx
git add        WordUnion/FatherSide.asmx
git add        WordUnion/FindTheWordThatMakesThePercentageOfTheWord.asmx
git add        WordUnion/Full-TextSearch.asmx
git add        WordUnion/Full-TextSearchHisWord.asmx
git add        WordUnion/Full-TextSearchRelease2018-05-20.asmx
git add        WordUnion/Full-TextSearchRelease2018-05-20T0800.asmx
git add        WordUnion/FullPositionWebService.asmx
git add        WordUnion/GodTitle.asmx
git add        WordUnion/GreekWebService.asmx
git add        WordUnion/HeActedHisWillOut.asmx
git add        WordUnion/HeActedHisWillOutArchive.asmx
git add        WordUnion/HeFinallyShowedItToMe.asmx
git add        WordUnion/HeIsHalfGone.asmx
git add        WordUnion/HisWord.asmx
git add        WordUnion/HobiGoUp.asmx
git add        WordUnion/HowWeWouldLearnToSay.asmx
git add        WordUnion/IAmNotForgotten.asmx
git add        WordUnion/IAmTotallyInterestedInAForeignKey.asmx
git add        WordUnion/IHaveKnowItForTwentySix.asmx
git add        WordUnion/IRealizeMyFullSenseInMakingMan.asmx
git add        WordUnion/IThinkInAfricaWaterDryRelease2018-05-20T1800.asmx
git add        WordUnion/InDefine.asmx
git add        WordUnion/IsMakingRemainderOfTime.asmx
git add        WordUnion/JeshuaBrothers.asmx
git add        WordUnion/LastAfter.asmx
git add        WordUnion/LifesNormancy.asmx
git add        WordUnion/LovingLiving.asmx
git add        WordUnion/MakingTodayAMemoryOfTomorrow.asmx
git add        WordUnion/MapTime.asmx
git add        WordUnion/MeISupposeInTime.asmx
git add        WordUnion/MyCondemn.asmx
git add        WordUnion/NaturalOccurringSequenceWebService.asmx
git add        WordUnion/NothingBeyondMeIsAcceptableToMe.asmx
git add        WordUnion/NumberSignWebService.asmx
git add        WordUnion/OftenTimeIsTheGuise.asmx
git add        WordUnion/OneForTheForbiddenBoy.asmx
git add        WordUnion/OneOfTheFamousWebsiteIKnowThrewUsByComfortAsYouGoTo.asmx
git add        WordUnion/OurPeople.asmx
git add        WordUnion/OurPeopleArchive.asmx
git add        WordUnion/OurTypeAtTheEnd.asmx
git add        WordUnion/People.asmx
git add        WordUnion/PhraseTwoOrMoreWordsThatReOccur.asmx
git add        WordUnion/RepeatedWords.asmx
git add        WordUnion/SQLServerManagementObjectsSMO.asmx
git add        WordUnion/SQLServerManagementObjectsSMOArchive.asmx
git add        WordUnion/SQLServerManagementObjectsSMORelease2019-09-27.asmx
git add        WordUnion/SQLToHTMLTable.asmx
git add        WordUnion/SchemaWebService.asmx
git add        WordUnion/ScriptureReferenceWebServiceRelease2018-05-19T1900.asmx
git add        WordUnion/ScriptureReferenceWebServiceRelease2018-05-19T1915.asmx
git add        WordUnion/ShowingAPersonHowHeIsTrulyIs.asmx
git add        WordUnion/StatedInTheBible.asmx
git add        WordUnion/StatedInTheBibleArchive.asmx
git add        WordUnion/SternIsTheBloodyNameOfTheSin.asmx
git add        WordUnion/SysColumns.asmx
git add        WordUnion/TheLastTimeArchive.asmx
git add        WordUnion/TheTripAmong.asmx
git add        WordUnion/TheTripAmongArchive.asmx
git add        WordUnion/ThinkLikeIThinkYouWouldThink.asmx
git add        WordUnion/ThisPaperWillArgueTheSumOfCost.asmx
git add        WordUnion/ToACertainDegreeLetManSeemHimself.asmx
git add        WordUnion/ToBeginAtTheLeastIsToSeeTheResemblance.asmx
git add        WordUnion/ToHaveLiveALifeIAmAProveOf.asmx
git add        WordUnion/ToHaveLiveALifeIAmAProveOfRelease2018-04-23T2130.asmx
git add        WordUnion/ToHaveLiveALifeIAmAProveOfRelease2018-04-23T2145.asmx
git add        WordUnion/ToHaveLiveALifeIAmAProveOfRelease2018-04-24T0400.asmx
git add        WordUnion/ToHaveLiveALifeIAmAProveOfRelease2018-04-24T0800.asmx
git add        WordUnion/ToKnowMyPercentageOfMyScore.asmx
git add        WordUnion/ToLiveACompleteLifeIsNotToHaveSpentTheFewWebService.asmx
git add        WordUnion/ToRememberHisConversationAsMine.asmx
git add        WordUnion/ToRememberHisConversationAsMineArchive.asmx
git add        WordUnion/TypesTheBeing.asmx
git add        WordUnion/UserTechnologyWebService.asmx
git add        WordUnion/WhatAreTheRegularFactorInfluencingYourPerception.asmx
git add        WordUnion/WhatIsAcceptedAsAPersonIsAcceptedAsAGod.asmx
git add        WordUnion/WhatIsYourQuestOfInterestCommonGoalsWebService.asmx
git add        WordUnion/WhenIsFinallyFirst.asmx
git add        WordUnion/WhenIsHeLivingAsAFutureOfOurBeing.asmx
git add        WordUnion/WhenLifeChooseAPathLifeIsMadeOfAPart.asmx
git add        WordUnion/WithEveryDifferingToYourAdvantage.asmx
git add        WordUnion/WordMeaning.asmx
git add        WordUnion/WordToNumberWebService.asmx
git add        WordUnion/WorldRound.asmx
git add        WordUnion/YouCannotComeToMeUnlessYouAreSelfAloneWebService.asmx
git add        WordUnion/YouCantGoogleItOnFriday.asmx
git add        WordUnion/YouCantGoogleItOnFridayRelease2018-06-25T1612.asmx
git add        WordUnion/YouHaveIncludedInYouWebService.asmx
