        git add   IIS/WordEngineering/WordGroup/AccordingToManyIHaveSpoken.asmx
        git add   IIS/WordEngineering/WordGroup/AccordingToManyIHaveSpoken.html
        git add   IIS/WordEngineering/WordGroup/AccordingToManyIHaveSpokenArchive.asmx
        git add   IIS/WordEngineering/WordGroup/AccordingToManyIHaveSpokenArchive.html
        git add   IIS/WordEngineering/WordGroup/SeparateTheirDesireOfTheBible.asmx
        git add   IIS/WordEngineering/WordGroup/SeparateTheirDesireOfTheBible.html
        git add   IIS/WordEngineering/WordGroup/SeparateTheirDesireOfTheBibleArchive.asmx
        git add   IIS/WordEngineering/WordGroup/SheWalkedTowardInFourDays.asmx
        git add   IIS/WordEngineering/WordGroup/SheWalkedTowardInFourDays.html
        git add   IIS/WordEngineering/WordGroup/SheWalkedTowardInFourDaysArchive.asmx
        git add   IIS/WordEngineering/WordGroup/SheWalkedTowardInFourDaysArchive.html
        git add   IIS/WordEngineering/WordGroup/WhereIChoseIDetermineUse.asmx
        git add   IIS/WordEngineering/WordGroup/WhereIChoseIDetermineUse.html
        git add   IIS/WordEngineering/WordGroup/WhereIChoseIDetermineUseArchive.asmx
        git add   IIS/WordEngineering/WordUnion/9432.js
        git add   IIS/WordEngineering/WordUnion/9432Archive.js
        git add   IIS/WordEngineering/WordUnion/9432Release2020-06-13T1800.js
        git add   IIS/WordEngineering/WordUnion/BibleWord.html
        git add   IIS/WordEngineering/WordUnion/BibleWordArchive.html
        git add   IIS/WordEngineering/WordUnion/BibleWordWebService.asmx
        git add   IIS/WordEngineering/bin/InformationInTransit.dll
        git add   InformationInTransit/InformationInTransit.dll
        git add   InformationInTransit/ProcessCode/AccordingToManyIHaveSpoken.cs
        git add   InformationInTransit/ProcessCode/SeparateTheirDesireOfTheBible.cs
        git add   InformationInTransit/ProcessCode/SheWalkedTowardInFourDays.Archivecs
        git add   InformationInTransit/ProcessCode/SheWalkedTowardInFourDays.cs
        git add   InformationInTransit/ProcessCode/WhereIChoseIDetermineUse.Archivecs
        git add   InformationInTransit/ProcessCode/WhereIChoseIDetermineUse.cs
        git add   InformationInTransit/ProcessLogic/BibleQuery.cs
        git add   InformationInTransit/ProcessLogic/BibleWordHelper.cs
        git add   GitHub.com/2021-01-21T1718gitadd.cmd
