/*
SELECT 'ALTER DATABASE ' + name + ' SET READ_WRITE' 
FROM sys.databases
ORDER BY name
*/

/*
ALTER DATABASE Account SET READ_WRITE
ALTER DATABASE AManDevelopedInAll SET READ_WRITE
ALTER DATABASE AmericaWorkingFour SET READ_WRITE
ALTER DATABASE ASPNetDB SET READ_WRITE
ALTER DATABASE Bible SET READ_WRITE
ALTER DATABASE BibleDictionary SET READ_WRITE
ALTER DATABASE CodingSample SET READ_WRITE
ALTER DATABASE ComparingYourWordAsYourDeed SET READ_WRITE
ALTER DATABASE Confide SET READ_WRITE
ALTER DATABASE dbtLabs_DataBuildTool SET READ_WRITE
ALTER DATABASE DepositACode SET READ_WRITE
ALTER DATABASE Dictionary SET READ_WRITE
ALTER DATABASE DWConfiguration SET READ_WRITE
ALTER DATABASE DWDiagnostics SET READ_WRITE
ALTER DATABASE DWQueue SET READ_WRITE
ALTER DATABASE ElectronicCopy SET READ_WRITE
ALTER DATABASE Generative SET READ_WRITE
ALTER DATABASE Gutenberg SET READ_WRITE
ALTER DATABASE HomeAbroad SET READ_WRITE
ALTER DATABASE IHaveDecidedToWorkOnAGradualImprovingSystem SET READ_WRITE
ALTER DATABASE InternetDictionaryProjectIDP SET READ_WRITE
ALTER DATABASE IShallBeTheirInheritance SET READ_WRITE
ALTER DATABASE IweKiko SET READ_WRITE
ALTER DATABASE model SET READ_WRITE
ALTER DATABASE msdb SET READ_WRITE
ALTER DATABASE OMatePro SET READ_WRITE
ALTER DATABASE RatingRank SET READ_WRITE
ALTER DATABASE RobertRouseVizBible SET READ_WRITE
ALTER DATABASE SoughtOut SET READ_WRITE
ALTER DATABASE SQLSharp SET READ_WRITE
ALTER DATABASE UnifiedModelingLanguage SET READ_WRITE
ALTER DATABASE URI SET READ_WRITE
ALTER DATABASE UserDb SET READ_WRITE
ALTER DATABASE UsualPassage SET READ_WRITE
ALTER DATABASE WhatWillInvolveLifeAsOurPart SET READ_WRITE
ALTER DATABASE WordEngineering SET READ_WRITE
*/

SELECT 'ALTER DATABASE ' + name + ' SET COMPATIBILITY_LEVEL = 170 '
FROM sys.databases
ORDER BY name


/*
ALTER DATABASE Account SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE AManDevelopedInAll SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE AmericaWorkingFour SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE ASPNetDB SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE Bible SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE BibleDictionary SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE CodingSample SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE ComparingYourWordAsYourDeed SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE Confide SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE dbtLabs_DataBuildTool SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE DepositACode SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE Dictionary SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE DWConfiguration SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE DWDiagnostics SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE DWQueue SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE ElectronicCopy SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE Generative SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE Gutenberg SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE HomeAbroad SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE IHaveDecidedToWorkOnAGradualImprovingSystem SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE InternetDictionaryProjectIDP SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE IShallBeTheirInheritance SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE IweKiko SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE master SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE model SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE msdb SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE OMatePro SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE RatingRank SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE RobertRouseVizBible SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE SoughtOut SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE SQLSharp SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE tempdb SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE UnifiedModelingLanguage SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE URI SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE UserDb SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE UsualPassage SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE WhatWillInvolveLifeAsOurPart SET COMPATIBILITY_LEVEL = 170 
ALTER DATABASE WordEngineering SET COMPATIBILITY_LEVEL = 170 
*/

/*
SELECT 'ALTER DATABASE ' + name + ' SET READ_ONLY' 
FROM sys.databases
ORDER BY name
*/

/*
ALTER DATABASE Account SET READ_ONLY
ALTER DATABASE AManDevelopedInAll SET READ_ONLY
ALTER DATABASE AmericaWorkingFour SET READ_ONLY
ALTER DATABASE ASPNetDB SET READ_ONLY
ALTER DATABASE Bible SET READ_ONLY
ALTER DATABASE BibleDictionary SET READ_ONLY
ALTER DATABASE CodingSample SET READ_ONLY
ALTER DATABASE ComparingYourWordAsYourDeed SET READ_ONLY
ALTER DATABASE Confide SET READ_ONLY
ALTER DATABASE dbtLabs_DataBuildTool SET READ_ONLY
ALTER DATABASE DepositACode SET READ_ONLY
ALTER DATABASE Dictionary SET READ_ONLY
ALTER DATABASE DWConfiguration SET READ_ONLY
ALTER DATABASE DWDiagnostics SET READ_ONLY
ALTER DATABASE DWQueue SET READ_ONLY
ALTER DATABASE ElectronicCopy SET READ_ONLY
ALTER DATABASE Generative SET READ_ONLY
ALTER DATABASE Gutenberg SET READ_ONLY
ALTER DATABASE HomeAbroad SET READ_ONLY
ALTER DATABASE IHaveDecidedToWorkOnAGradualImprovingSystem SET READ_WRITE
ALTER DATABASE InternetDictionaryProjectIDP SET READ_ONLY
ALTER DATABASE IShallBeTheirInheritance SET READ_ONLY
ALTER DATABASE IweKiko SET READ_ONLY
ALTER DATABASE model SET READ_ONLY
ALTER DATABASE msdb SET READ_ONLY
ALTER DATABASE OMatePro SET READ_ONLY
ALTER DATABASE RatingRank SET READ_ONLY
ALTER DATABASE RobertRouseVizBible SET READ_ONLY
ALTER DATABASE SoughtOut SET READ_ONLY
ALTER DATABASE SQLSharp SET READ_ONLY
ALTER DATABASE UnifiedModelingLanguage SET READ_ONLY
ALTER DATABASE URI SET READ_WRITE
ALTER DATABASE UserDb SET READ_ONLY
ALTER DATABASE UsualPassage SET READ_ONLY
ALTER DATABASE WhatWillInvolveLifeAsOurPart SET READ_ONLY
ALTER DATABASE WordEngineering SET READ_WRITE
*/
