SELECT 'ALTER DATABASE ' + Name + ' SET READ_WRITE WITH NO_WAIT; ' FROM master.sys.databases
/*
ALTER DATABASE master SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE tempdb SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE model SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE msdb SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE DWDiagnostics SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE DWConfiguration SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE DWQueue SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE Account SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE AManDevelopedInAll SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE AmericaWorkingFour SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE ASPNetDB SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE Bible SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE BibleDictionary SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE CodingSample SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE ComparingYourWordAsYourDeed SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE Confide SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE dbtLabs_DataBuildTool SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE DepositACode SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE Dictionary SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE ElectronicCopy SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE Generative SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE Gutenberg SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE HomeAbroad SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE IHaveDecidedToWorkOnAGradualImprovingSystem SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE InternetDictionaryProjectIDP SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE IShallBeTheirInheritance SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE IweKiko SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE OMatePro SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE RatingRank SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE RobertRouseVizBible SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE SoughtOut SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE SQLSharp SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE UnifiedModelingLanguage SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE URI SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE UserDb SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE UsualPassage SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE WhatWillInvolveLifeAsOurPart SET READ_WRITE WITH NO_WAIT; 
ALTER DATABASE WordEngineering SET READ_WRITE WITH NO_WAIT; 
*/

SELECT 'ALTER DATABASE ' + Name + ' SET READ_ONLY WITH NO_WAIT; ' FROM master.sys.databases

/*
ALTER DATABASE master SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE tempdb SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE model SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE msdb SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE DWDiagnostics SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE DWConfiguration SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE DWQueue SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE Account SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE AManDevelopedInAll SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE AmericaWorkingFour SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE ASPNetDB SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE Bible SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE BibleDictionary SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE CodingSample SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE ComparingYourWordAsYourDeed SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE Confide SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE dbtLabs_DataBuildTool SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE DepositACode SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE Dictionary SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE ElectronicCopy SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE Generative SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE Gutenberg SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE HomeAbroad SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE IHaveDecidedToWorkOnAGradualImprovingSystem SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE InternetDictionaryProjectIDP SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE IShallBeTheirInheritance SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE IweKiko SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE OMatePro SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE RatingRank SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE RobertRouseVizBible SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE SoughtOut SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE SQLSharp SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE UnifiedModelingLanguage SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE URI SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE UserDb SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE UsualPassage SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE WhatWillInvolveLifeAsOurPart SET READ_ONLY WITH NO_WAIT; 
ALTER DATABASE WordEngineering SET READ_ONLY WITH NO_WAIT; 
*/