<%@ Page Language="C#" AutoEventWireup="true" CodeFile="DateCompute.aspx.cs" Inherits="WordEngineering.DateCompute" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
	<link rel="stylesheet" type="text/css" href="9432.css">
    <title>DateCompute</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <table>
            <tr>
                <td>
                    <asp:Label
                        ID="labelDatedFrom"
                        runat="server"
                        AssociatedControlID="datedFrom"
                        Text="From"
                    />
                </td>
                <td>                    
                    <asp:TextBox 
                        ID="datedFrom"
                        runat="server"
                    />                        
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        ID="labelYears"
                        runat="server"
                        AssociatedControlID="years"
                        Text="Years"
                    />
                </td>
                <td>                    
                    <asp:TextBox 
                        ID="years"
                        runat="server"
                    />
                </td>
                <td>
                    <asp:Label
                        ID="labelMonths"
                        runat="server"
                        AssociatedControlID="months"
                        Text="Months"
                    />
                </td>
                <td>                    
                    <asp:TextBox 
                        ID="months"
                        runat="server"
                    />
                </td>
                <td>
                    <asp:Label
                        ID="labelWeeks"
                        runat="server"
                        AssociatedControlID="weeks"
                        Text="Weeks"
                    />
                </td>
                <td>                    
                    <asp:TextBox 
                        ID="weeks"
                        runat="server"
                    />
                </td>
                <td>
                    <asp:Label
                        ID="labelDays"
                        runat="server"
                        AssociatedControlID="days"
                        Text="Days"
                    />
                </td>
                <td>                    
                    <asp:TextBox 
                        ID="days"
                        runat="server"
                    />
                </td>
			</tr>
            <tr>
                <td colspan="2">
                    <asp:Button
                        ID="submit"
                        runat="server"
                        OnClick="Submit_Click"
                        Text="Submit"
                    />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:Label
                        ID="datedTo"
                        runat="server"
                    />
                </td>
            </tr>
        </table>
    </div>
    </form>
</body>
</html>
