WordEngineering: #http://docs.getdbt.com/docs/core/connect-data-platform/mssql-setup
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: comfort
      port: 1433
      database: WordEngineering
      schema: dbo
      windows_login: True
      encrypt: false
      trust_cert: True