@Echo Off
Call TheWord ChristianLayman.orgChristianLaymanChurchRoyTinklenberg278GrandAvenueOakland94610CAUSAJunko.comJunkoNishiguchiCheng_20041228MadeInJapanCheeseSomeCheeseSoPereelCanWezeelAStorm.xml