@ECHO OFF
TheWord Comforter_-_20031211YouDon'tHavePassengers_IDon'tKnowWhatToSayILoveYou_ColorDullRaMiJoyExceedsNecessity_WhenYouTurnTheirIsNoOneThereButCareToTheOneAnotherBigBig.xml  Comforter_-_20031211YouDon'tHavePassengers_IDon'tKnowWhatToSayILoveYou_ColorDullRaMiJoyExceedsNecessity_WhenYouTurnTheirIsNoOneThereButCareToTheOneAnotherBigBig.txt
TheWord Comforter_-_20031212WithoutTheCloudsWhiterTheClouds_MerryGoSings.xml  Comforter_-_20031212WithoutTheCloudsWhiterTheClouds_MerryGoSings.txt
TheWord Comforter_-_20031212TheDoorIsInHeaven.xml  Comforter_-_20031212TheDoorIsInHeaven.txt
TheWord Comforter_-_20031212YouDon'tHaveTheBeastLineYouAreMyBeastLine.xml   Comforter_-_20031212YouDon'tHaveTheBeastLineYouAreMyBeastLine.txt