@ECHO OFF
TheWordAlphabetSequence   Comforter_-_20040905OtisSpunkMeyerIAmCoachingThisTeamButWhileIAmPlayingAwayHowMuchOfTheHomeCrowdFollowsMe_Laboratious_CanTheModelSitOffClassAndHaveABaby.txt  Comforter_-_20040905TheWordAlphabetSequenceOtisSpunkMeyerIAmCoachingThisTeamButWhileIAmPlayingAwayHowMuchOfTheHomeCrowdFollowsMe_Laboratious_CanTheModelSitOffClassAndHaveABaby.xml
