@ECHO OFF
TheWord Comforter_-_20031122WhenIKnowIWillMissYouThat'sWhenISaidKnowAllTheWay.xml      Comforter_-_20031122WhenIKnowIWillMissYouThat'sWhenISaidKnowAllTheWay.txt
TheWord Comforter_-_20031123IAskYouToBuildAPlaceForYouToLiveIn_IStillCallGodHome.xml   Comforter_-_20031123IAskYouToBuildAPlaceForYouToLiveIn_IStillCallGodHome.txt