@ECHO OFF
TheWord Comforter_-_20031209AlwaysInMyPocket.xml               Comforter_-_20031209AlwaysInMyPocket.txt
TheWord Comforter_-_20031209VitorFerreiraBorbaRivaldo.xml      Comforter_-_20031209VitorFerreiraBorbaRivaldo.txt
TheWord Comforter_-_20031210ToMakeItHavingParticipateInIt.xml  Comforter_-_20031210ToMakeItHavingParticipateInIt.txt
TheWord Comforter_-_20031210IWillBeDamned.xml                  Comforter_-_20031210IWillBeDamned.txt
TheWord Comforter_-_20031210FruitfulnessWithoutMercyIsNonsense_IDon'tKnowHow-toShedBloodForMoney.xml   Comforter_-_20031210FruitfulnessWithoutMercyIsNonsense_IDon'tKnowHow-toShedBloodForMoney.txt
TheWord Comforter_-_20031211YouDon'tHavePassengers_IDon'tKnowWhatToSayILoveYou_ColorDullRaMiJoyExceedsNecessity_WhenYouTurnTheirIsNoOneThereButCareToTheOneAnotherBigBig.xml   Comforter_-_20031211YouDon'tHavePassengers_IDon'tKnowWhatToSayILoveYou_ColorDullRaMiJoyExceedsNecessity_WhenYouTurnTheirIsNoOneThereButCareToTheOneAnotherBigBig.txt