@ECHO OFF
TheWordAlphabetSequence   Comforter_-_20040906Todai_txtUselessOfAType_YouFoundFriendsBehavingLikeYou_OverseasInSemiUnderpants_NoAdversaryCounterOffensive.txt   Comforter_-_20040906TheWordAlphabetSequenceTodai_txtUselessOfAType_YouFoundFriendsBehavingLikeYou_OverseasInSemiUnderpants_NoAdversaryCounterOffensive.xml
