@ECHO OFF
TheWordAlphabetSequence   Comforter_-_20040906Todai_UselessOfAType_YouFoundFriendsBehavingLikeYou_OverseasInSemiUnderpants_NoAdversaryCounterOffensive.txt   Comforter_-_20040906TheWordAlphabetSequenceTodai_UselessOfAType_YouFoundFriendsBehavingLikeYou_OverseasInSemiUnderpants_NoAdversaryCounterOffensive.xml
