@ECHO OFF
TheWord Comforter_-_20040115LidoSupermarket_ImperialTaste_HwaTai_PerfectFoodManufacturing_Albertsons_RoundyApparel_FoodRaimentHandWordStewardship.xml   Comforter_-_20040115LidoSupermarket_ImperialTaste_HwaTai_PerfectFoodManufacturing_Albertsons_RoundyApparel_FoodRaimentHandWordStewardship.txt
