@ECHO OFF
TheWord Comforter_-_20040319TheyAreTheFirstPeopleToFightForChristianity_BudgetCutter.xml   Comforter_-_20040319TheWordTheyAreTheFirstPeopleToFightForChristianity_BudgetCutter.xml
TheWord Comforter_-_20040320JehovahRophe_MadderMurder_WoefulUpbringing.xml                 Comforter_-_20040320TheWordJehovahRophe_MadderMurder_WoefulUpbringing.xml