@ECHO OFF
TheWordAlphabetSequence  Comforter_-_20040204MyThai_FlowWithTrafficWhenTrafficIsFlowingYou.txt    Comforter_-_20040204TheWordAlphabetSequenceMyThai_FlowWithTrafficWhenTrafficIsFlowingYou.xml