@ECHO OFF
TheWordAlphabetSequence  Comforter_-_20040518Orinse_AManOfAuthorityIsAccustomedToGoodLiving.txt  Comforter_-_20040518TheWordAlphabetSequenceOrinse_AManOfAuthorityIsAccustomedToGoodLiving.xml