@ECHO OFF
TheWord Comforter_-_20031206MayBeTheEggsTeaWillBeOk_LobaIjaOja_TheWordRainbowClockwise.xml                                                                            Comforter_-_20031206MayBeTheEggsTeaWillBeOk_LobaIjaOja_TheWordRainbowClockwise.txt
TheWord Comforter_-_20031206ThyKingComeThisDay_AllBatsAreHere_WeFun_FoSoKe_It'sRainingAndYouLetMeInSoISayLetMeReciprocate.xml                                         Comforter_-_20031206ThyKingComeThisDay_AllBatsAreHere_WeFun_FoSoKe_It'sRainingAndYouLetMeInSoISayLetMeReciprocate.txt
TheWord Comforter_-_20031206GodInAllYourMightYou'veNotForgivenMeButYouHaveForgottenMySorrows_NowIAmKindToGodBecauseGodHasBeenKindToMe_ShirtedInGuest'sClothing.xml    Comforter_-_20031206GodInAllYourMightYou'veNotForgivenMeButYouHaveForgottenMySorrows_NowIAmKindToGodBecauseGodHasBeenKindToMe_ShirtedInGuest'sClothing.txt
TheWord Comforter_-_20031207FavoritismEndsRacism.xml                                                                                                                  Comforter_-_20031207FavoritismEndsRacism.txt
TheWord Comforter_-_20031207YagoMeji_OtiYagoMeji_OtiYaIwe.xml                                                                                                         Comforter_-_20031207YagoMeji_OtiYagoMeji_OtiYaIwe.txt      
TheWord Comforter_-_20031125HIISaveMoney_IWriteTheLetterWriteTheLoveTheGreatestThingInSexIsTheLove.xml                                                                Comforter_-_20031125HIISaveMoney_IWriteTheLetterWriteTheLoveTheGreatestThingInSexIsTheLove.txt
TheWord Comforter_-_20031207LobaKinseOba.xml                                                                                                                          Comforter_-_20031207LobaKinseOba.txt
TheWord Comforter_-_20031207CouldITurnMyChildrenAwayAndHopeToBeWithYou.xml                                                                                            Comforter_-_20031207CouldITurnMyChildrenAwayAndHopeToBeWithYou.txt
TheWord Comforter_-_20031207IjemiIrekun.xml                                                                                                                           Comforter_-_20031207IjemiIrekun.txt
TheWord Comforter_-_20031207IAmSufficientForYouOh_FromTheGoingForthOfTheCommandmentToRepayJerusalemAndTheMessiahThePrinceAndTheMessiahThePrinceShallBeRepayedInTroubledTimes.xml    Comforter_-_20031207IAmSufficientForYouOh_FromTheGoingForthOfTheCommandmentToRepayJerusalemAndTheMessiahThePrinceAndTheMessiahThePrinceShallBeRepayedInTroubledTimes.txt