@ECHO OFF
TheWord Comforter_-_20031127ThanksgivingTodaiCircumciseGodHasLovedHimMoreThanAllOfUs_AnOfferingOfMight_FloodOfMemories_GodItDoesn'tTakeAManOrTwoItTakesOnlyMe_YouHaveToKnowHowToDoThings.xml  Comforter_-_20031127ThanksgivingTodaiCircumciseGodHasLovedHimMoreThanAllOfUs_AnOfferingOfMight_FloodOfMemories_GodItDoesn'tTakeAManOrTwoItTakesOnlyMe_YouHaveToKnowHowToDoThings.txt
TheWord Comforter_-_20031127ThanksgivingTodaiCircumciseHeUnderstoodAgain.xml  Comforter_-_20031127ThanksgivingTodaiCircumciseHeUnderstoodAgain.txt
TheWord Comforter_-_20031127Menotti.xml  Comforter_-_20031127Menotti.txt
TheWord Comforter_-_20031128GodAskedHimAQuestionAndHeSaidThisIsTheAnswerIMustGoOnAndIMustMigrate_TakeMeInAndIWillTakeYouIn.xml  Comforter_-_20031128GodAskedHimAQuestionAndHeSaidThisIsTheAnswerIMustGoOnAndIMustMigrate_TakeMeInAndIWillTakeYouIn.txt
TheWord Comforter_-_20031128DoUnderstandMeAndIWillUnderstandYouDoLoveMeAndIWillLoveYou_UnderstandMeLove.xml   Comforter_-_20031128DoUnderstandMeAndIWillUnderstandYouDoLoveMeAndIWillLoveYou_UnderstandMeLove.txt
TheWord Comforter_-_20031128IRe-dedicate_AyoIkoyiBoilerPlates_FourAids.xml  Comforter_-_20031128IRe-dedicate_AyoIkoyiBoilerPlates_FourAids.txt
TheWord Comforter_-_20031129AManOfTremendousWealth.xml  Comforter_-_20031129AManOfTremendousWealth.txt