@Echo Off
Call TheWord LidoFaireLOVTaqueriaLosGallosAlbertsonsSafewayKaiserLogitech_-_20041214TheFullLawIsTheGovernmentInAPenitentiaryIDoHaveAChildIJustDon'tKnowTheManInFactorOfHimInputAcceptableOutputDerivable.xml
Call TheWord ISEB.orgIslamicSocietyOfEastBay33330PeaceTerraceFremont94555_-_20041214ItIsTrulyIsn'tMenialIfIDoKnowThemICanHelpInAPleasantWay.xml
Call TheWord Svenhards.comSvenhard'sSwedishBakeryOakland94607-2596CAUSA800705-3379_Ajax.nl_-_20041214ItIsOnlyAvailableInTheLastCenturyAndSoIDoNeedYouLeadingInWhoseJetInYardageDash.xml
Call Rhema /bennyHinn:../URI/20041215URIWordEngineering.xml
Call TheWord PenskeBaxterKinderCareChabotCollege.edu_-_20041215ManLessDrivenSeekIndependentViewSurrogateRelationshipsFeelFitterUniversalClothingUnrestrictedUnusualEnvironmentLimitPassLuxuryTenderedHandsExpendable.xml
Call Rhema /bennyHinn:../URI/20041215URIChrist.xml
Call TheWord Baxter_-_20041216TrendYearTwoFourThreeHeWasTheMatronInTheOverseaHanger.xml
Call TheWord CarlZeiss_-_20041216IThinkYouRepresentGoodNeighborhoodTheseAreOurClassyCitizen.xml
Call TheWord ChoYonggiYoidoFullGospelChurch_-_20041217AttentionRedShirtAngryIsThreeFiftySevenForeverIsSoulSoSomePeopleHaveSomeWordsToSayToYouWhatDoSixTwoVersalCookingNoMoreEnglishIWillBeFiguringOutAWayToCook.xml