@Echo Off
SQLCMD –E –d WordEngineering –i ..\Documentation\Comforter.org\20041224HouseKeepingURI.sql
Call Rhema /bennyHinn:../URI/20041223URIWordEngineering.xml
Call TheWord 20041224DoYouDrinkBarryScottOSimpleAtThisCostInTheOtherEndDon'tCommitLegalBoundageMrEmekaICan'tLentTemptationFaithbuilderPointCoding.xml
Call Rhema /bennyHinn:../URI/20041224URIChrist.xml
Call TheWord 20041225IWorkoutArriveTheSonStoodAtTheSeventhWallTriumphAthensWaitAMinuteWhenBelshazzarShallBeAnnoyedWithYouIWillStickHimAndHeShallDieFillAllYourCupFilledWeStoleOnAWoodyHelmsonWoodyHelmCaliforniaAvenue.xml
Call TheWord 20041226PrivateEverythingCreativityWorkNeedCareCircuitCityStefanStefanice.xml
Call TheWord 20041227HallelujahYouCanTreasureYouAreATeamBoredRealThingWe'veBeenThroughThisDisease.xml
Call TheWord 20041227You'veLostSemanticLeadershipTheirIsANewBlueprintForLifeInTransistionStruggle.xml
Call ..\WordOfGod\UtilityUnicodeBuild.bat
Call TheWord ChristianLayman.orgChristianLaymanChurchRoyTinklenberg278GrandAvenueOakland94610CAUSAJunko.comJunkoNishiguchiCheng_20041228MadeInJapanCheeseSomeCheeseSoPereelCanWezeelAStorm.xml
Call TheWord 20041229TheyMovedJuneLastYearICanLookAtTheCentralOfLife.xml
Call TheWord T-Mobile.com_-_20041229LargestImpressionGodInprintLifestyleEnrollScholarshipTrustPersonIdentityAdditiveStimulateInhabitYieldYetMostBornWrapEarlyAncestry.xml
Call SQLCMD –E –d WordEngineering –i ..\Documentation\VeliciaKim19630424\VeliciaKim19630424_-_20041229.sql
Call TheWord CafeDoBrasil.web.comCafeDoBrasilRestaurantChurrascariaBar1106MarketStreetSanFrancisco94102CAUSAElviaSantos_-_20041230ShareViewSponsorTerrorWindWiseIncentiveFatalTypeSocialThornHedge.xml
Call TheWord CafeDoBrasil.web.comCafeDoBrasilRestaurantChurrascariaBar1106MarketStreetSanFrancisco94102CAUSAElviaSantos_-_20041230PrimarySustenancePrivilegeFewGatheringMirrorMirageSeparateYemisiGoRaiseMarupe.xml
Call TheWord CafeDoBrasil.web.comCafeDoBrasilRestaurantChurrascariaBar1106MarketStreetSanFrancisco94102CAUSAElviaSantos_-_20041231YouAreEverythingToMeIWillDoEverythingCouldn'tSitTheSeaYouAreEverywhere.xml