<%@ Page 
    Language="C#" 
    AutoEventWireup="true" 
    CodeFile="MongoDBBook.aspx.cs"
    Inherits="WordEngineering.MongoDBBookPage" 
%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
	<head runat="Server" id="HeadBook">
		<title runat="Server" id="TitleBook">Book</title>
	</head>
	<body runat="server" id="BodyContact">
	<form 
		ID="FormContact" 
		runat="server"
		enctype="multipart/form-data"    
		autocomplete="on"
		defaultbutton="search"
		defaultfocus="question"
	>
	<table align="center" border="0">
		<tbody>
			<tr align="center">
				<td align="center">
					Search Query
				</td>
			</tr>

			<tr align="center">
				<td align="center">
					<asp:Label
						runat="Server"
						ID="labelAuthor"
						Text="Author:"
						AssociatedControlID="question"
					/>	
					<asp:TextBox
						runat="Server"
						ID="question"
						TabIndex="1"
					/>        
					<asp:Button runat="server" id="search"  onclick="Search_Click"  Text="Search" TabIndex="19" />
				</td>      
			</tr>
		</tbody>
    </table>

    <table align="center" border="0">
		<tbody>
			<tr align="center">
				<td>
					<asp:GridView
						id="BookGridView" 
						runat="server" 
						AllowPaging="True"
						AllowSorting="True" 
						AutoGenerateColumns="False"
						AutoGenerateDeleteButton="True"
						AutoGenerateEditButton="True"
						AutoGenerateSelectButton="True"
						OnPageIndexChanging="BookGridView_PageIndexChanging"
						OnRowCancelingEdit="BookGridView_RowCancelingEdit"
						OnRowDeleting="BookGridView_RowDeleting"
						OnRowEditing="BookGridView_RowEditing"
						OnRowUpdating="BookGridView_RowUpdating"
						OnSorting="BookGridView_Sorting"
						PageSize="10"
						SelectedIndex="0"
						ShowFooter="True"
					>
						<HeaderStyle BackColor='#CCCC99'/>

						<RowStyle BackColor='#eeeeee'/>
				
						<AlternatingRowStyle BackColor='#ffffe8'/>

						<Columns>
							<asp:TemplateField
								HeaderText="Author"
								SortExpression="Author"
							>
								<ItemTemplate>
									<asp:Label
										Runat="Server"
										id="LabelBookGridViewItemTemplate_Id" 
										Text='<%# Eval("_Id") %>'
										Style="display: none"
									/>
									<asp:Label
										Runat="Server"
										id="LabelBookGridViewItemTemplateAuthor" 
										Text='<%# Eval("Author") %>'
									/>
								</ItemTemplate>
								<EditItemTemplate>
									<asp:Label
										Runat="Server"
										id="LabelBookGridViewEditItemTemplate_Id" 
										Text='<%# Eval("Author") %>'
										Style="display: none"
									/>
									<asp:TextBox 
										Runat="Server"
										id="TextBoxBookGridViewEditItemTemplateAuthor" 
										Text='<%# Bind("Author") %>'
									/>
								</EditItemTemplate>
								<FooterTemplate>
									<asp:TextBox 
										Runat="Server"
										id="TextBoxBookGridViewFooterTemplateAuthor"
										Text='<%# Bind("Author") %>'
									/>
								</FooterTemplate>
							</asp:TemplateField>
							
							<asp:TemplateField
								HeaderText="Title"
								SortExpression="Title"
							>
								<ItemTemplate>
									<asp:Label
										Runat="Server"
										id="LabelBookGridViewItemTemplateTitle" 
										Text='<%# Eval("Title") %>'
									/>
								</ItemTemplate>
								<EditItemTemplate>
									<asp:TextBox 
										Runat="Server"
										id="TextBoxBookGridViewEditItemTemplateTitle" 
										Text='<%# Bind("Title") %>'
									/>
								</EditItemTemplate>
								<FooterTemplate>
									<asp:TextBox 
										Runat="Server"
										id="TextBoxBookGridViewFooterTemplateTitle"
										Text='<%# Bind("Title") %>'
									/>
						            <asp:Button 
										Runat="Server"           
										ID="ButtonBookGridViewFooterTemplateAdd"
										OnClick="BookGridView_Insert"
										Text="Add"
									/>
								</FooterTemplate>
							</asp:TemplateField>
							
						</Columns>
					</asp:GridView>
				</td>
			</tr>
		</tbody>
    </table>

    <table align="center" border="0">
		<tbody> 
			<tr align="center">
				<td align="center">
					<asp:Literal 
						id="feedBack" 
						runat="server" 
						EnableViewState="False"
					/>
				</td>
			</tr>
		</tbody>    
    </table>

   </form>
 </body>
</html>
