git add        WordGroup/WantingMeToTheGrooveButTheGrooveDontTakeControlOfMeWantingMeToControlOfMyself.asmx
git add        WordGroup/WantingMeToTheGrooveButTheGrooveDontTakeControlOfMeWantingMeToControlOfMyself.html
git add        WordGroup/WantingMeToTheGrooveButTheGrooveDontTakeControlOfMeWantingMeToControlOfMyselfArchive.asmx
git add        WordGroup/WantingMeToTheGrooveButTheGrooveDontTakeControlOfMeWantingMeToControlOfMyselfArchive.html
git add        WordGroup/WhatDivideTheConcern.html
git add        WordGroup/WhatDivideTheConcernArchive.html
git add        WordGroup/WhatHisWordCanSayByDeedAlone.asmx
git add        WordGroup/WhatHisWordCanSayByDeedAlone.html
git add        WordGroup/WhatHisWordCanSayByDeedAloneArchive.asmx
git add        WordGroup/WhatHisWordCanSayByDeedAloneArchive.html
git add        WordGroup/WhatKindOfPlacesDoYouGuysLikeGoingTo.html
git add        WordGroup/WhatKindOfPlacesDoYouGuysLikeGoingToArchive.html
git add        WordGroup/WhatKindOfPlacesDoYouGuysLikeGoingToRelease2020-11-03T1320.html
git add        WordGroup/WhatRolesAreMentionMostInTheBible.Archiveasmx
git add        WordGroup/WhatRolesAreMentionMostInTheBible.asmx
git add        WordGroup/WhatRolesAreMentionMostInTheBible.html
git add        WordGroup/WhatRolesAreMentionMostInTheBibleArchive.html
git add        WordGroup/WhatSetsUsApartIsHowWeAreFavorableAtUse.asmx
git add        WordGroup/WhatSetsUsApartIsHowWeAreFavorableAtUse.html
git add        WordGroup/WhatSetsUsApartIsHowWeAreFavorableAtUseArchive.asmx
git add        WordGroup/WhatSetsUsApartIsHowWeAreFavorableAtUseArchive.html
git add        WordGroup/WhatTimeIsItPleaseNineFortyNine.html
git add        WordGroup/WhatTimeIsItPleaseNineFortyNineArchive.html
git add        WordGroup/WhenDoWeDwarfOurPrivilege.asmx
git add        WordGroup/WhenDoWeDwarfOurPrivilege.html
git add        WordGroup/WhenDoWeDwarfOurPrivilegeArchive.asmx
git add        WordGroup/WhenDoWeDwarfOurPrivilegeArchive.html
git add        WordGroup/WhenEmptynessIsFarAway.asmx
git add        WordGroup/WhenEmptynessIsFarAway.html
git add        WordGroup/WhenEmptynessIsFarAwayArchive.asmx
git add        WordGroup/WhenEmptynessIsFarAwayArchive.html
git add        WordGroup/WhenNothingUpToDateIsFurtherMore.asmx
git add        WordGroup/WhenNothingUpToDateIsFurtherMore.html
git add        WordGroup/WhenNothingUpToDateIsFurtherMoreArchive.asmx
git add        WordGroup/WhenNothingUpToDateIsFurtherMoreArchive.html
git add        WordGroup/WhenOneSeldomlyDoWhatIsRightOneSeldomlyDoWhatIsMeans.html
git add        WordGroup/WhenOneSeldomlyDoWhatIsRightOneSeldomlyDoWhatIsMeansArchive.html
git add        WordGroup/WhenOneSeldomlyDoWhatIsRightOneSeldomlyDoWhatIsMeansRelease2019-01-10T1900.html
git add        WordGroup/WhenThePastorIsPreachingYouDontWithTheScriptureToComeInSubsequent.asmx
git add        WordGroup/WhenThePastorIsPreachingYouDontWithTheScriptureToComeInSubsequent.html
git add        WordGroup/WhenThePastorIsPreachingYouDontWithTheScriptureToComeInSubsequentArchive.asmx
git add        WordGroup/WhenThePastorIsPreachingYouDontWithTheScriptureToComeInSubsequentArchive.html
git add        WordGroup/WhereYouWillLiveForeverThatIsWhatIHaveChosenForYou.html
git add        WordGroup/WhereYouWillLiveForeverThatIsWhatIHaveChosenForYouArchive.html
git add        WordGroup/WhichBookMentionsNumberTheMost.asmx
git add        WordGroup/WhichBookMentionsNumberTheMost.html
git add        WordGroup/WhichBookMentionsNumberTheMostArchive.asmx
git add        WordGroup/WhichBookMentionsNumberTheMostArchive.html
git add        WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGood.asmx
git add        WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGood.html
git add        WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGoodArchive.asmx
git add        WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGoodArchive.html
git add        WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGoodRelease2019-12-22T1501.asmx
git add        WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGoodRelease2019-12-22T1501.html
git add        WordGroup/WordOccurrences.asmx
git add        WordGroup/WordOccurrences.html
git add        WordGroup/WordOccurrencesArchive.asmx
git add        WordGroup/WordOccurrencesArchive.html
git add        WordGroup/WordOccurrencesRelease2020-01-09T1922.asmx
git add        WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMoving.asmx
git add        WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMoving.html
git add        WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMovingArchive.asmx
git add        WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMovingArchive.html
git add        WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMovingRelease2019-12-09T1742.asmx
git add        WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMovingRelease2019-12-09T1900.html
git add        WordGroup/YouDontNeedAHornet.asmx
git add        WordGroup/YouDontNeedAHornet.html
git add        WordGroup/YouDontNeedAHornetArchive.asmx
git add        WordGroup/YouDontNeedAHornetArchive.html
git add        WordGroup/YouJustFakeOneTakeOne.asmx
git add        WordGroup/YouJustFakeOneTakeOne.html
git add        WordGroup/YouJustFakeOneTakeOneArchive.asmx
git add        WordGroup/YouJustFakeOneTakeOneArchive.html
git add        WordGroup/YourPartOfTheHistory.asmx
git add        WordGroup/YourPartOfTheHistory.html
git add        WordGroup/YourPartOfTheHistoryArchive.asmx
git add        WordGroup/YourPartOfTheHistoryArchive.html
git add        WordGroup/YourPartOfTheHistoryRelease2019-12-18T0130.html
git add        WordGroup/YourPartOfTheHistoryRelease2019-12-18T0140.asmx