        git add    IIS/WordEngineering/WordGroup/APerhapsCompare.html
        git add    IIS/WordEngineering/WordGroup/APerhapsCompareArchive.html
        git add    IIS/WordEngineering/WordGroup/AProveOfWhereIAmExisting.html
        git add    IIS/WordEngineering/WordGroup/AProveOfWhereIAmExistingArchive.html
        git add    IIS/WordEngineering/WordGroup/AmericaWorkingFour.html
        git add    IIS/WordEngineering/WordGroup/AmericaWorkingFourArchive.html
        git add    IIS/WordEngineering/WordGroup/AnAccurateMeasureOfThePresentIsHowFarIAdvanceIt.html
        git add    IIS/WordEngineering/WordGroup/AnAccurateMeasureOfThePresentIsHowFarIAdvanceItArchive.html
        git add    IIS/WordEngineering/WordGroup/AndThePriestSaidAreOneOnlyForMe.html
        git add    IIS/WordEngineering/WordGroup/AndThePriestSaidAreOneOnlyForMeArchive.html
        git add    IIS/WordEngineering/WordGroup/AsStepsLearnFromGod.html
        git add    IIS/WordEngineering/WordGroup/AsStepsLearnFromGod2019-06-04T1515.html
        git add    IIS/WordEngineering/WordGroup/AsStepsLearnFromGodArchive.html
        git add    IIS/WordEngineering/WordGroup/AsWeSaidOmoSchoolYinNaTryOhunNaMakeEffort.html
        git add    IIS/WordEngineering/WordGroup/AsWeSaidOmoSchoolYinNaTryOhunNaMakeEffortArchive.html
        git add    IIS/WordEngineering/WordGroup/BibleBookIDTitleChapterVerse.html
        git add    IIS/WordEngineering/WordGroup/BibleBookIDTitleChapterVerseArchive.html
        git add    IIS/WordEngineering/WordGroup/BibleBooksReduceFilter.html
        git add    IIS/WordEngineering/WordGroup/BibleBooksReduceFilterArchive.html
        git add    IIS/WordEngineering/WordGroup/BigInteger.html
        git add    IIS/WordEngineering/WordGroup/BigIntegerArchive.html
        git add    IIS/WordEngineering/WordGroup/BigIntegerDelegateOperation.html
        git add    IIS/WordEngineering/WordGroup/BigIntegerDelegateOperationArchive.html
        git add    IIS/WordEngineering/WordGroup/BringWaterDown.html
        git add    IIS/WordEngineering/WordGroup/BringWaterDownArchive.html
        git add    IIS/WordEngineering/WordGroup/BringWaterDownRelease2020-09-13T2125.html
        git add    IIS/WordEngineering/WordGroup/ConcatenateTableColumns.html
        git add    IIS/WordEngineering/WordGroup/ConcatenateTableColumns2020-04-06T1900.html
        git add    IIS/WordEngineering/WordGroup/ConcatenateTableColumnsArchive.html
        git add    IIS/WordEngineering/WordGroup/Countrycode.org.html
        git add    IIS/WordEngineering/WordGroup/Countrycode.orgArchive.html
        git add    IIS/WordEngineering/WordGroup/Eventuate.html
        git add    IIS/WordEngineering/WordGroup/EventuateArchive.html
        git add    IIS/WordEngineering/WordGroup/EventuateRelease2018-12-01T0015.html
        git add    IIS/WordEngineering/WordGroup/EventuateRelease2019-11-24T1639.html
        git add    IIS/WordEngineering/WordGroup/EventuateRelease2019-11-24T1645.html
        git add    IIS/WordEngineering/WordGroup/ExistsIn.html
        git add    IIS/WordEngineering/WordGroup/ExistsInArchive.html
        git add    IIS/WordEngineering/WordGroup/ExistsInRelease2020-02-23T1803.html
        git add    IIS/WordEngineering/WordGroup/FivePointFourEightOnePointFourEight.html
        git add    IIS/WordEngineering/WordGroup/FivePointFourEightOnePointFourEightArchive.html
        git add    IIS/WordEngineering/WordGroup/GarbageCollector.html
        git add    IIS/WordEngineering/WordGroup/GarbageCollectorArchive.html
        git add    IIS/WordEngineering/WordGroup/GenealogyGeneration.html
        git add    IIS/WordEngineering/WordGroup/GenealogyGenerationArchive.html
        git add    IIS/WordEngineering/WordGroup/GermanIsDetermineToAriseToTheGristlyFifteenYearsAgo.html
        git add    IIS/WordEngineering/WordGroup/GermanIsDetermineToAriseToTheGristlyFifteenYearsAgoArchive.html
        git add    IIS/WordEngineering/WordGroup/HadBeenWrittenToTheChurches.html
        git add    IIS/WordEngineering/WordGroup/HadBeenWrittenToTheChurchesArchive.html
        git add    IIS/WordEngineering/WordGroup/HowYouMakeUseOfHisOwn.html
        git add    IIS/WordEngineering/WordGroup/HowYouMakeUseOfHisOwn2019-07-11T1200.html
        git add    IIS/WordEngineering/WordGroup/HowYouMakeUseOfHisOwnArchive.html
        git add    IIS/WordEngineering/WordGroup/HoweverOurProgressArePersonal.html
        git add    IIS/WordEngineering/WordGroup/HoweverOurProgressArePersonalArchive.html
        git add    IIS/WordEngineering/WordGroup/IKnowAsDoing.html
        git add    IIS/WordEngineering/WordGroup/IKnowAsDoingArchive.html
        git add    IIS/WordEngineering/WordGroup/IWillLliftItUpIDontTearItByName.html
        git add    IIS/WordEngineering/WordGroup/IWillLliftItUpIDontTearItByNameArchive.html
        git add    IIS/WordEngineering/WordGroup/IWillTakeThemUpForTakingMyDelay.html
        git add    IIS/WordEngineering/WordGroup/IWillTakeThemUpForTakingMyDelayArchive.html
        git add    IIS/WordEngineering/WordGroup/IWillTakeThemUpForTakingMyDelayRelease2018-09-25T1700.html
        git add    IIS/WordEngineering/WordGroup/IWillTakeThemUpForTakingMyDelayRelease2019-11-27T1802.html
        git add    IIS/WordEngineering/WordGroup/IWillTakeThemUpForTakingMyDelayRelease2019-11-27T1812.html
        git add    IIS/WordEngineering/WordGroup/InTimeAnswerPast.html
        git add    IIS/WordEngineering/WordGroup/InTimeAnswerPastArchive.html
        git add    IIS/WordEngineering/WordGroup/InYourKindnessYouHaveNotExcludedMe.html
        git add    IIS/WordEngineering/WordGroup/InYourKindnessYouHaveNotExcludedMe2020-12-03T2048.html
        git add    IIS/WordEngineering/WordGroup/InYourKindnessYouHaveNotExcludedMeArchive.html
        git add    IIS/WordEngineering/WordGroup/InYourKindnessYouHaveNotExcludedMeRelease2020-12-03T1827.html
        git add    IIS/WordEngineering/WordGroup/InYourKindnessYouHaveNotExcludedMeRelease2020-12-03T1944.html
        git add    IIS/WordEngineering/WordGroup/InYourKindnessYouHaveNotExcludedMeRelease2020-12-03T2130.html
        git add    IIS/WordEngineering/WordGroup/JesusToSacrificeEverythingToSacrificeAll.html
        git add    IIS/WordEngineering/WordGroup/JesusToSacrificeEverythingToSacrificeAllArchive.html
        git add    IIS/WordEngineering/WordGroup/July1951NineteenFiftyOne.html
        git add    IIS/WordEngineering/WordGroup/July1951NineteenFiftyOneArchive.html
        git add    IIS/WordEngineering/WordGroup/JumpOverTheThirteenth.html
        git add    IIS/WordEngineering/WordGroup/JumpOverTheThirteenthArchive.html
        git add    IIS/WordEngineering/WordGroup/ListCount.html
        git add    IIS/WordEngineering/WordGroup/ListCountArchive.html
        git add    IIS/WordEngineering/WordGroup/LivedBeyondTheWilderness.html
        git add    IIS/WordEngineering/WordGroup/LivedBeyondTheWildernessArchive.html
        git add    IIS/WordEngineering/WordGroup/MakingITrueIsLeftToNoOneEspeciallyUpToMe.html
        git add    IIS/WordEngineering/WordGroup/MakingITrueIsLeftToNoOneEspeciallyUpToMeArchive.html
        git add    IIS/WordEngineering/WordGroup/MostlyAbsentFact.html
        git add    IIS/WordEngineering/WordGroup/MostlyAbsentFactArchive.html
        git add    IIS/WordEngineering/WordGroup/NeedingWhereIAm.html
        git add    IIS/WordEngineering/WordGroup/NeedingWhereIAmArchive.html
        git add    IIS/WordEngineering/WordGroup/NorthCarolinaWantToHaveOurOwnNavy_CarolWasVotingForChiefLeye.html
        git add    IIS/WordEngineering/WordGroup/NorthCarolinaWantToHaveOurOwnNavy_CarolWasVotingForChiefLeyeArchive.html
        git add    IIS/WordEngineering/WordGroup/NotHappyWithAPlaceClassX.html
        git add    IIS/WordEngineering/WordGroup/NotHappyWithAPlaceClassXArchive.html
        git add    IIS/WordEngineering/WordGroup/NotHappyWithAPlaceClassXRelease2018-11-24T0030.html
        git add    IIS/WordEngineering/WordGroup/NotHappyWithAPlaceClassXRelease2020-11-26T1725.html
        git add    IIS/WordEngineering/WordGroup/OjoToOhunBaPariPeluWon.html
        git add    IIS/WordEngineering/WordGroup/OjoToOhunBaPariPeluWonArchive.html
        git add    IIS/WordEngineering/WordGroup/OpenBucket.html
        git add    IIS/WordEngineering/WordGroup/OpenBucketArchive.html
        git add    IIS/WordEngineering/WordGroup/OutsideOfTheWordWhatIsYourOwn.html
        git add    IIS/WordEngineering/WordGroup/OutsideOfTheWordWhatIsYourOwnArchive.html
        git add    IIS/WordEngineering/WordGroup/PaulWhoCouldTalkAboutYouIndividualProsperity.html
        git add    IIS/WordEngineering/WordGroup/PaulWhoCouldTalkAboutYouIndividualProsperityArchive.html
        git add    IIS/WordEngineering/WordGroup/PrecedeMyTalking.html
        git add    IIS/WordEngineering/WordGroup/PrecedeMyTalkingArchive.html
        git add    IIS/WordEngineering/WordGroup/PressureByYourTeamMetAtY.html
        git add    IIS/WordEngineering/WordGroup/PressureByYourTeamMetAtYArchive.html
        git add    IIS/WordEngineering/WordGroup/ProcessViewer.html
        git add    IIS/WordEngineering/WordGroup/ProcessViewerArchive.html
        git add    IIS/WordEngineering/WordGroup/ReferringToHimAsMyWork.html
        git add    IIS/WordEngineering/WordGroup/ReferringToHimAsMyWorkArchive.html
        git add    IIS/WordEngineering/WordGroup/SeparateTheirDesireOfTheBible.html
        git add    IIS/WordEngineering/WordGroup/SeparateTheirDesireOfTheBibleArchive.html
        git add    IIS/WordEngineering/WordGroup/ServingWho.html
        git add    IIS/WordEngineering/WordGroup/ServingWhoArchive.html
        git add    IIS/WordEngineering/WordGroup/SheWalkedTowardInFourDays.html
        git add    IIS/WordEngineering/WordGroup/SheWalkedTowardInFourDaysArchive.html
        git add    IIS/WordEngineering/WordGroup/TheDaysHeGivesUsIsFullAheadThereIsUponChange.html
        git add    IIS/WordEngineering/WordGroup/TheDaysHeGivesUsIsFullAheadThereIsUponChangeArchive.html
        git add    IIS/WordEngineering/WordGroup/TheFansMayThinkYouAreFromADifferentCompanyYouAreFromADifferentKind.html
        git add    IIS/WordEngineering/WordGroup/TheFansMayThinkYouAreFromADifferentCompanyYouAreFromADifferentKindArchive.html
        git add    IIS/WordEngineering/WordGroup/TheLoveOfResemblance.html
        git add    IIS/WordEngineering/WordGroup/TheLoveOfResemblanceArchive.html
        git add    IIS/WordEngineering/WordGroup/TheMid-TermFromMid-TermIsWhatAllowForChanges.html
        git add    IIS/WordEngineering/WordGroup/TheMid-TermFromMid-TermIsWhatAllowForChangesArchive.html
        git add    IIS/WordEngineering/WordGroup/TheNeglectityOfDesire.html
        git add    IIS/WordEngineering/WordGroup/TheNeglectityOfDesireArchive.html
        git add    IIS/WordEngineering/WordGroup/TheNeglectityOfDesireRelease2020-03-30T2300.html
        git add    IIS/WordEngineering/WordGroup/TheNightWasOverWhenIWas_HeCelebrateHimselfOverYou.html
        git add    IIS/WordEngineering/WordGroup/TheNightWasOverWhenIWas_HeCelebrateHimselfOverYouArchive.html
        git add    IIS/WordEngineering/WordGroup/TheResponsibilityPlacedOnReasoning.html
        git add    IIS/WordEngineering/WordGroup/TheResponsibilityPlacedOnReasoningArchive.html
        git add    IIS/WordEngineering/WordGroup/ThereAreNoTalkingLanguage.html
        git add    IIS/WordEngineering/WordGroup/ThereAreNoTalkingLanguageArchive.html
        git add    IIS/WordEngineering/WordGroup/ThisIsTheEventInTheirLives.html
        git add    IIS/WordEngineering/WordGroup/ThisIsTheEventInTheirLivesArchive.html
        git add    IIS/WordEngineering/WordGroup/ThisIsTheEventInTheirLivesRelease2019-08-17T0750.html
        git add    IIS/WordEngineering/WordGroup/ThisIsTheEventInTheirLivesRelease2019-08-17T0900.html
        git add    IIS/WordEngineering/WordGroup/ThisIsTheEventInTheirLivesRelease2019-08-17T1000.html
        git add    IIS/WordEngineering/WordGroup/TimeHasAdjustedAsTheEvent.html
        git add    IIS/WordEngineering/WordGroup/TimeHasAdjustedAsTheEventArchive.html
        git add    IIS/WordEngineering/WordGroup/TimeHasAdjustedAsTheEventRelease2019-03-23T1326.html
        git add    IIS/WordEngineering/WordGroup/TinBaSoleMiMaWago.html
        git add    IIS/WordEngineering/WordGroup/TinBaSoleMiMaWagoArchive.html
        git add    IIS/WordEngineering/WordGroup/TinBaSoleMiMaWagoRelease2020-11-05T1630.html
        git add    IIS/WordEngineering/WordGroup/ToLookAtTheAspirationOfKind.html
        git add    IIS/WordEngineering/WordGroup/ToLookAtTheAspirationOfKindArchive.html
        git add    IIS/WordEngineering/WordGroup/ToMostExpectMyName.html
        git add    IIS/WordEngineering/WordGroup/ToMostExpectMyNameArchive.html
        git add    IIS/WordEngineering/WordGroup/TypeViewer.html
        git add    IIS/WordEngineering/WordGroup/TypeViewerArchive.html
        git add    IIS/WordEngineering/WordGroup/URIView.html
        git add    IIS/WordEngineering/WordGroup/URIViewArchive.html
        git add    IIS/WordEngineering/WordGroup/WantingMeToTheGrooveButTheGrooveDontTakeControlOfMeWantingMeToControlOfMyself.html
        git add    IIS/WordEngineering/WordGroup/WantingMeToTheGrooveButTheGrooveDontTakeControlOfMeWantingMeToControlOfMyselfArchive.html
        git add    IIS/WordEngineering/WordGroup/WhatHisWordCanSayByDeedAlone.html
        git add    IIS/WordEngineering/WordGroup/WhatHisWordCanSayByDeedAloneArchive.html
        git add    IIS/WordEngineering/WordGroup/WhatRolesAreMentionMostInTheBible.html
        git add    IIS/WordEngineering/WordGroup/WhatRolesAreMentionMostInTheBibleArchive.html
        git add    IIS/WordEngineering/WordGroup/WhatSetsUsApartIsHowWeAreFavorableAtUse.html
        git add    IIS/WordEngineering/WordGroup/WhatSetsUsApartIsHowWeAreFavorableAtUseArchive.html
        git add    IIS/WordEngineering/WordGroup/WhenDoWeDwarfOurPrivilege.html
        git add    IIS/WordEngineering/WordGroup/WhenDoWeDwarfOurPrivilegeArchive.html
        git add    IIS/WordEngineering/WordGroup/WhenEmptynessIsFarAway.html
        git add    IIS/WordEngineering/WordGroup/WhenEmptynessIsFarAwayArchive.html
        git add    IIS/WordEngineering/WordGroup/WhenNothingUpToDateIsFurtherMore.html
        git add    IIS/WordEngineering/WordGroup/WhenNothingUpToDateIsFurtherMoreArchive.html
        git add    IIS/WordEngineering/WordGroup/WhenThePastorIsPreachingYouDontWithTheScriptureToComeInSubsequent.html
        git add    IIS/WordEngineering/WordGroup/WhenThePastorIsPreachingYouDontWithTheScriptureToComeInSubsequentArchive.html
        git add    IIS/WordEngineering/WordGroup/WhichBookMentionsNumberTheMost.html
        git add    IIS/WordEngineering/WordGroup/WhichBookMentionsNumberTheMostArchive.html
        git add    IIS/WordEngineering/WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGood.html
        git add    IIS/WordEngineering/WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGoodArchive.html
        git add    IIS/WordEngineering/WordGroup/WhoIsYourManagerCrazyMisterMartinMisterMartinAsAGoodRelease2019-12-22T1501.html
        git add    IIS/WordEngineering/WordGroup/WordOccurrences.html
        git add    IIS/WordEngineering/WordGroup/WordOccurrencesArchive.html
        git add    IIS/WordEngineering/WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMoving.html
        git add    IIS/WordEngineering/WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMovingArchive.html
        git add    IIS/WordEngineering/WordGroup/WroteToTheRomanEmpireAskingToReleasePaulAndYetSheJustWasntMovingRelease2019-12-09T1900.html
        git add    IIS/WordEngineering/WordGroup/YouDontNeedAHornet.html
        git add    IIS/WordEngineering/WordGroup/YouDontNeedAHornetArchive.html
        git add    IIS/WordEngineering/WordGroup/YouJustFakeOneTakeOne.html
        git add    IIS/WordEngineering/WordGroup/YouJustFakeOneTakeOneArchive.html
        git add    IIS/WordEngineering/WordGroup/YourPartOfTheHistory.html
        git add    IIS/WordEngineering/WordGroup/YourPartOfTheHistoryArchive.html
        git add    IIS/WordEngineering/WordGroup/YourPartOfTheHistoryRelease2019-12-18T0130.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-11-17.html
