        git add    Batch/2017-01-02DoingSomething.bat
        git add    Batch/2017-01-02DoingSomethingArchive.bat
        git add    IIS/WordEngineering/Resume/KenAdenijiResume.html
        git add    IIS/WordEngineering/Resume/KenAdenijiResume.pdf
        git add    IIS/WordEngineering/Resume/KenAdenijiResume.txt
        git add    IIS/WordEngineering/Resume/KenAdenijiResumeArchive.html
        git add    IIS/WordEngineering/Resume/KenAdenijiResumeRelease2020-08-21.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.pdf
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.pdf
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionArchive.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionRelease2020-11-26.html

git add        GitHub.com/2021-09-28T2231GitHub.bat
git add        GitHub.com/2021-09-28T2231GitHubArchive.bat		
git add        IIS/WordEngineering/Images/CT_SkillTest_v3.psd
git add        IIS/WordEngineering/Interview/CoalitionTechnologies.com/
git add        PowerShell/Microsoft/
