        git add   Batch/2017-01-02DoingSomething.bat
        git add   Batch/2017-01-02DoingSomethingArchive.bat
        git add   IIS/WordEngineering/Resume/KenAdenijiResume.html
        git add   IIS/WordEngineering/Resume/KenAdenijiResume.pdf
        git add   IIS/WordEngineering/Resume/KenAdenijiResumeArchive.html
        git add   IIS/WordEngineering/Resume/KenAdenijiResumeRelease2020-08-21.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.pdf
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html
        git add   IIS/WordEngineering/WordUnion/9432.css
        git add   IIS/WordEngineering/WordUnion/9432Archive.css

git add        GitHub.com/2021-08-18T1237GitHub.bat
git add        GitHub.com/2021-08-18T1237GitHubArchive.bat
git add        IIS/WordEngineering/CascadingStyleSheet/DavidSawyerMcFarland_Missing@SawMac.com/
git add        IIS/WordEngineering/JavaScript/Airbnb/
git add        IIS/WordEngineering/JavaScript/Algorithm/JSZip.html
git add        IIS/WordEngineering/JavaScript/Algorithm/JSZipArchive.html
