        git add   IIS/WordEngineering/Web.config
        git add   IIS/WordEngineering/WebArchive.config
        git add   IIS/WordEngineering/bin/InformationInTransit.dll
        git add   InformationInTransit/DataAccess/DataCommand.cs
        git add   InformationInTransit/InformationInTransit.dll
        git rm    InformationInTransit/ProcessCode/BibleBookCompareEquality.Archivecs
        git rm    InformationInTransit/ProcessCode/BibleBookCompareEquality.cs
        git rm    InformationInTransit/ProcessCode/BibleBookCompareEquality.exe
        git add   InformationInTransit/ProcessLogic/BibleBookHelper.cs
        git add   InformationInTransit/ProcessLogic/BiblicalCalendarHelper.cs
        git add   InformationInTransit/ProcessLogic/Exact.cs
        git add   InformationInTransit/ProcessLogic/HeIsHalfGoneHelper.cs
        git add   InformationInTransit/ProcessLogic/IValueMostWhereIAmPurposelyUse.cs
        git add   InformationInTransit/ProcessLogic/IataAirportCode.cs
        git add   InformationInTransit/ProcessLogic/MeetMyEndThrough.cs
        git add   InformationInTransit/ProcessLogic/OurTypeAtTheEndHelper.cs
        git add   InformationInTransit/ProcessLogic/PeopleHelper.cs
        git add   InformationInTransit/ProcessLogic/PhraseTwoOrMoreWordsThatReOccur.cs
        git add   InformationInTransit/ProcessLogic/SysColumnsHelper.cs
        git add   InformationInTransit/ProcessLogic/Terminus.cs
        git add   InformationInTransit/ProcessLogic/ToMostExtentOfTalent.cs
        git add   InformationInTransit/ProcessLogic/TypesTheBeingHelper.cs
        git add   InformationInTransit/ProcessLogic/WhenIsHeLivingAsAFutureOfOurBeingHelper.cs
        git add   InformationInTransit/ProcessLogic/WordEntrance.cs
        git add   InformationInTransit/ProcessLogic/WordMeaningHelper.cs
		
        git add         IIS/WordEngineering/Isaiah35v3-7/
        git add 		IIS/WordEngineering/Linux/MySQL/
        git add         IIS/WordEngineering/WebRelease2021-04-24T1510.config
        git add         IIS/WordEngineering/bin/MySql.Data.EntityFramework.dll
        git add         IIS/WordEngineering/bin/MySql.Data.EntityFramework.xml
        git add         IIS/WordEngineering/bin/MySql.Data.InstallState
        git add         IIS/WordEngineering/bin/MySql.Data.dll
        git add         IIS/WordEngineering/bin/MySql.Data.xml
        git add         IIS/WordEngineering/bin/MySql.Web.dll
        git add         IIS/WordEngineering/bin/MySql.Web.xml
        git add         IIS/WordEngineering/robotsRelease2021-04-21T2131.txt
        git add         InformationInTransit/ChristianNagel/XMLReaderAndWriterSample.2021-03-16cs
        git add         InformationInTransit/DataAccess/DataCommand.Release2021-04-24T1456cs
        git add         InformationInTransit/ProcessCode/MySQLODBCConnection.Archivecs
        git add         InformationInTransit/ProcessCode/MySQLODBCConnection.cs
        git add         InformationInTransit/ProcessCode/SQLServerODBCConnection.Archivecs
        git add         InformationInTransit/ProcessCode/SQLServerODBCConnection.cs
        git add         InformationInTransit/ProcessCode/SQLServerODBCConnection.exe
        git add         InformationInTransit/ProcessCode/mysql.cs
        git add         InformationInTransit/ProcessCode/mysql.exe		