git add   Batch/2017-01-02DoingSomething.bat
git add   Batch/2017-01-02DoingSomethingArchive.bat
git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.html
git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.pdf
git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionArchive.html
git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionRelease2020-11-26.html
git add   IIS/WordEngineering/WordUnion/BecauseWeAreHellThisIsOurDefinition.html
git add   IIS/WordEngineering/WordUnion/BecauseWeAreHellThisIsOurDefinitionArchive.html
git add   IIS/WordEngineering/WordGroup/WillTargetTuesdayDecember31st.html
git add   IIS/WordEngineering/WordGroup/WillTargetTuesdayDecember31stArchive.html
