        git add    Batch/2017-01-02DoingSomething.bat
        git add    Batch/2017-01-02DoingSomethingArchive.bat
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.pdf
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionArchive.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionRelease2020-11-26.html

git add        GitHub.com/2021-12-18T1329GitHub.bat
git add        GitHub.com/2021-12-18T1329GitHubArchive.bat
git add        IIS/WordEngineering/WordCross/ParseAFileAndGenerateTheHyperlink.html
git add        IIS/WordEngineering/WordCross/ParseAFileAndGenerateTheHyperlinkArchive.html
git add        IIS/WordEngineering/WordCross/SeOKa.asmx
git add        IIS/WordEngineering/WordCross/SeOKa.html
git add        IIS/WordEngineering/WordCross/SeOKaArchive.asmx
git add IIS/WordEngineering/WordCross/SeOKaArchive.html
git add IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.txt
