        git add   IIS/WordEngineering/Resume/KenAdenijiResume.html
        git add   IIS/WordEngineering/Resume/KenAdenijiResumeArchive.html
        git add   IIS/WordEngineering/Resume/KenAdenijiResumeRelease2020-08-21.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html
        git add   IIS/WordEngineering/WordUnion/9432.css
        git add   IIS/WordEngineering/WordUnion/9432Archive.css
        git add   IIS/WordEngineering/WordUnion/9432Release2021-01-08T2043.css
