        git add     Batch/2017-01-02DoingSomething.bat
        git add     Batch/2017-01-02DoingSomethingArchive.bat
        git add     IIS/WordEngineering/Resume/KenAdenijiResume.html
        git add     IIS/WordEngineering/Resume/KenAdenijiResume.pdf
        git add     IIS/WordEngineering/Resume/KenAdenijiResumeArchive.html
        git add     IIS/WordEngineering/Resume/KenAdenijiResumeRelease2020-08-21.html
        git add     IIS/WordEngineering/Web.config
        git add     IIS/WordEngineering/bin/InformationInTransit.dll
        git rm      IIS/WordEngineering/robots.txt
        git rm      InformationInTransit/ChristianNagel/XMLReaderAndWriterSample.cs
        git add     InformationInTransit/DataAccess/DataCommand.Archivecs
        git add     InformationInTransit/DataAccess/DataCommand.cs
        git add     InformationInTransit/InformationInTransit.dll
        git add     InformationInTransit/ProcessLogic/BibleBookHelper.cs
        git add     InformationInTransit/ProcessLogic/BiblicalCalendarHelper.cs
        git add     InformationInTransit/ProcessLogic/Exact.cs
        git add     InformationInTransit/ProcessLogic/HeIsHalfGoneHelper.cs
        git add     InformationInTransit/ProcessLogic/IValueMostWhereIAmPurposelyUse.cs
        git add     InformationInTransit/ProcessLogic/IataAirportCode.cs
        git add     InformationInTransit/ProcessLogic/MeetMyEndThrough.cs
        git add     InformationInTransit/ProcessLogic/OurTypeAtTheEndHelper.cs
        git add     InformationInTransit/ProcessLogic/PeopleHelper.cs
        git add     InformationInTransit/ProcessLogic/PhraseTwoOrMoreWordsThatReOccur.cs
        git add     InformationInTransit/ProcessLogic/SysColumnsHelper.cs
        git add     InformationInTransit/ProcessLogic/Terminus.cs
        git add     InformationInTransit/ProcessLogic/ToMostExtentOfTalent.cs
        git add     InformationInTransit/ProcessLogic/TypesTheBeingHelper.cs
        git add     InformationInTransit/ProcessLogic/WhenIsHeLivingAsAFutureOfOurBeingHelper.cs
        git add     InformationInTransit/ProcessLogic/WordEntrance.cs
        git add     InformationInTransit/ProcessLogic/WordMeaningHelper.cs

        git add		GitHub.com/2021-04-20T2127gitadd.bat
        git add		GitHub.com/2021-04-20T2127gitaddArchive.bat
		git add		2021-04-24T1732gitadd.bat
		git add		2021-04-24T1732gitaddArchive.bat
		