        git add    Batch/2017-01-02DoingSomething.bat
        git add    Batch/2017-01-02DoingSomethingArchive.bat
        git add    IIS/WordEngineering/Isaiah35v3-7/Isaiah35v3-7.html
        git add    IIS/WordEngineering/Isaiah35v3-7/Isaiah35v3-7Archive.html
        git add    IIS/WordEngineering/WordGroup/EveningMorning.asmx
        git add    IIS/WordEngineering/WordGroup/EveningMorning.html
        git add    IIS/WordEngineering/WordGroup/EveningMorningArchive.asmx
        git add    IIS/WordEngineering/WordGroup/EveningMorningArchive.html
        git add    IIS/WordEngineering/WordGroup/WhenGoodThingsHappen.html
        git add    IIS/WordEngineering/WordGroup/WhenGoodThingsHappenArchive.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.pdf
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.pdf
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionArchive.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionRelease2020-11-26.html
        git add    IIS/WordEngineering/WordUnion/9432.css
git add            GitHub.com/2021-04-26T1705gitadd.bat
git add            GitHub.com/2021-04-26T1705gitaddArchive.bat
git add            GitHub.com/2021-04-27T2330gitadd.bat
git add            GitHub.com/2021-04-27T2330gitaddArchive.bat
