        git add   IIS/WordEngineering/Resume/2020-04-17Skill.html
        git add   IIS/WordEngineering/Resume/2020-04-17Skill.txt
        git add   IIS/WordEngineering/Resume/2020-04-17SkillArchive.html
        git add   IIS/WordEngineering/Resume/2020-04-17SkillArchive.txt
        git add   IIS/WordEngineering/Resume/KenAdenijiSkillSet.html
        git add   IIS/WordEngineering/WordCross/JustThirtyOneDaysDivided.html
        git add   IIS/WordEngineering/WordCross/JustThirtyOneDaysDividedArchive.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.pdf
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionArchive.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionRelease2020-11-26.html
git add        GitHub.com/2021-08-26T0352GitHub.bat
git add        GitHub.com/2021-08-26T0352GitHubArchive.bat
git add        IIS/WordEngineering/Resume/KenAdenijiSkillSetArchive.html
