        git add IIS/WordEngineering/WordGroup/BecauseToBeHonestThisIsTooStarefic.html
        git add IIS/WordEngineering/WordGroup/BecauseToBeHonestThisIsTooStareficArchive.html
		git add InformationInTransit/ProcessCode/OftenTime.cs
		git add InformationInTransit/ProcessCode/OftenTime.Archivecs
        git add IIS/WordEngineering/WordGroup/OftenTime.html
        git add IIS/WordEngineering/WordGroup/OftenTimeArchive.html
        git add IIS/WordEngineering/WordGroup/OftenTime.asmx
        git add  IIS/WordEngineering/WordGroup/OftenTimeArchive.asmx
        git add IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html
        git add IIS/WordEngineering/bin/InformationInTransit.dll
        git add InformationInTransit/InformationInTransit.dll
git add         GitHub.com/2021-03-05T1752gitadd.bat
git add         GitHub.com/2021-03-05T1752gitaddArchive.bat