        git add   Batch/2017-01-02DoingSomething.bat
        git add   Batch/2017-01-02DoingSomethingArchive.bat
        git add   IIS/WordEngineering/FederalAviationAuthorityFAA.gov/InternationalAirTransportAssociation.asmx
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.pdf
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.pdf
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionArchive.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionRelease2020-11-26.html
        git add   InformationInTransit/DataAccess/DataCommand.cs
        git add   InformationInTransit/ProcessLogic/IataAirportCode.cs

git add IIS/WordEngineering/FederalAviationAuthorityFAA.gov/InternationalAirTransportAssociationArchive.asmx
git add IIS/WordEngineering/Linux/2021-09-18T2200LearningTheBashShell/
git add IIS/WordEngineering/WordCross/TheVoiceOfGermanyTheEndOfGermany.asmx
git add IIS/WordEngineering/WordCross/TheVoiceOfGermanyTheEndOfGermany.html
git add IIS/WordEngineering/WordCross/TheVoiceOfGermanyTheEndOfGermanyArchive.asmx
git add IIS/WordEngineering/WordCross/TheVoiceOfGermanyTheEndOfGermanyArchive.html
git add InformationInTransit/ProcessLogic/IataAirportCode.exe
git add InformationInTransit/ProcessLogic/IataAirportCode2021-09-17T1201.cs
git add InformationInTransit/ProcessLogic/IataAirportCode2021-09-17T1208.cs
