        git add    Batch/2017-01-02DoingSomething.bat
        git add    Batch/2017-01-02DoingSomethingArchive.bat
        git add    IIS/WordEngineering/WordCross/DiscoverPowerShell.html
        git add    IIS/WordEngineering/WordCross/DiscoverPowerShellArchive.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.pdf
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.pdf
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionArchive.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionRelease2020-11-26.html
        git add    IIS/WordEngineering/bin/InformationInTransit.dll
        git add    InformationInTransit/InformationInTransit.dll
        git add    InformationInTransit/InformationInTransitBuild.bat
        git add    InformationInTransit/InformationInTransitBuildArchive.bat

git add        GitHub.com/2021-11-09T1746GitHub.bat
git add        GitHub.com/2021-11-09T1746GitHubArchive.bat
git add        IIS/WordEngineering/WordCross/WhatSubstitutionLiesAhead.asmx
git add        IIS/WordEngineering/WordCross/WhatSubstitutionLiesAhead.html
git add        IIS/WordEngineering/WordCross/WhatSubstitutionLiesAheadArchive.asmx
git add        IIS/WordEngineering/WordCross/WhatSubstitutionLiesAheadArchive.html
git add        IIS/WordEngineering/bin/System.Management.Automation.dll
git add        InformationInTransit/System.Management.Automation.dll
git add        InformationInTransit/bin/Debug/System.Management.Automation.dll
git add        PowerShell/PowerShellExplained.comWithKevinMarquette/
