        git add    Batch/2017-01-02DoingSomething.bat
        git add    Batch/2017-01-02DoingSomethingArchive.bat
        git add    IIS/WordEngineering/Resume/KenAdenijiResume.html
        git add    IIS/WordEngineering/Resume/KenAdenijiResume.pdf
        git add    IIS/WordEngineering/Resume/KenAdenijiResume.txt
        git add    IIS/WordEngineering/Resume/KenAdenijiResumeArchive.html
        git add    IIS/WordEngineering/Resume/KenAdenijiResumeRelease2020-08-21.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.pdf
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html

git add        GitHub.com/2021-10-29T1855GitHub.bat
git add        GitHub.com/2021-10-29T1855GitHubArchive.bat
git add        InformationInTransit/LanguageIntegratedQueryLINQ/LINQQueryExpressionsBibleBook.Archivecs
git add        InformationInTransit/LanguageIntegratedQueryLINQ/LINQQueryExpressionsBibleBook.cs
git add        InformationInTransit/LanguageIntegratedQueryLINQ/LINQQueryExpressionsBibleBook.exe
git add        InformationInTransit/LanguageIntegratedQueryLINQ/LINQQueryExpressionsBibleBookBuild.bat
git add		   PowerShell/PowerShell101ByMikeFRobbins/
git add        PowerShell/TutorialsPoint.com/cmdlet.ps1
git add        PowerShell/TutorialsPoint.com/cmdletArchive.ps1
