        git add   GitHub.com/2022-05-12T1611GitHub.bat
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.pdf
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.txt
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.pdf
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionArchive.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionRelease2020-11-26.html
        git add   IIS/WordEngineering/WordUnion/9432.js
        git add   IIS/WordEngineering/WordUnion/9432Archive.js
        git add   IIS/WordEngineering/WordUnion/9432Release2020-06-13T1800.js
        git add   Python/WesMcKinney.com/wesmckinney.com_-_2022-05-10T1635NumPyArraysPentateuchArchive.sql
        git add   Python/WesMcKinney.com/wesmckinney.com_-_2022-05-11T2046FileInputOutputPentateuch.py
        git add   Python/WesMcKinney.com/wesmckinney.com_-_2022-05-11T2046FileInputOutputPentateuchArchive.py

git add        GitHub.com/2022-05-16T0041GitHub.bat
git add        IIS/WordEngineering/WordCross/ItIsNotHowMuchYouGiveItIsWhoYouGiveOhLORD.asmx
git add        IIS/WordEngineering/WordCross/ItIsNotHowMuchYouGiveItIsWhoYouGiveOhLORD.html
git add        IIS/WordEngineering/WordCross/ItIsNotHowMuchYouGiveItIsWhoYouGiveOhLORDArchive.asmx
git add        IIS/WordEngineering/WordCross/ItIsNotHowMuchYouGiveItIsWhoYouGiveOhLORDArchive.html
git add Python/WesMcKinney.com/BibleBook.Json.txt
