git add        GitHub.com/2022-05-05T1403GitHub.bat
git add        IIS/WordEngineering/WordCross/ADayToSubmitATimeToLookElsewhere.asmx
git add        IIS/WordEngineering/WordCross/ADayToSubmitATimeToLookElsewhere.html
git add        IIS/WordEngineering/WordCross/ADayToSubmitATimeToLookElsewhereArchive.asmx
git add        IIS/WordEngineering/WordCross/ADayToSubmitATimeToLookElsewhereArchive.html
git add		   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.pdf
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionArchive.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionRelease2020-11-26.html
