        git add   Batch/2017-01-02DoingSomething.bat
        git add   Batch/2017-01-02DoingSomethingArchive.bat
        git add   IIS/WordEngineering/WordCross/WhatWillYouFindThatPlace.html
        git add   IIS/WordEngineering/WordCross/WhatWillYouFindThatPlaceArchive.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.pdf
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add   IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.pdf
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionArchive.html
        git add   IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionRelease2020-11-26.html
git add        GitHub.com/2022-04-30T1702GitHub.bat
git add        IIS/WordEngineering/WordCross/JRSinclair.com_-_WhatSearchesAfterItselfWillNeverBeAppended.html
git add        IIS/WordEngineering/WordCross/JRSinclair.com_-_WhatSearchesAfterItselfWillNeverBeAppendedArchive.html
