        git add    Batch/2017-01-02DoingSomething.bat
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertation.pdf
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationArchive.html
        git add    IIS/WordEngineering/WordUnion/2015-10-23DoctoralDissertationRelease2020-12-17.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescription.pdf
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionArchive.html
        git add    IIS/WordEngineering/WordUnion/2019-10-05ArtifactDescriptionRelease2020-11-26.html
        git rm    IIS/WordEngineering/bin/InformationInTransit.Release2016-12-28dll
        git rm    IIS/WordEngineering/bin/InformationInTransit.Release2016-12-28pdb
        git rm    IIS/WordEngineering/bin/InformationInTransit.Release2017-04-01T2122dll
        git rm    IIS/WordEngineering/bin/InformationInTransit.Release2018-03-21dll
        git rm    IIS/WordEngineering/bin/InformationInTransit.Release2019-04-28dll
        git rm    IIS/WordEngineering/bin/InformationInTransit.Release2019-06-21dll
        git rm    IIS/WordEngineering/bin/InformationInTransit.Release2019-08-16T1830dll
        git rm    InformationInTransit/bin/Debug/HtmlAgilityPack.XML
        git rm    InformationInTransit/bin/Debug/HtmlAgilityPack.dll
        git rm    InformationInTransit/bin/Debug/HtmlAgilityPack.pdb
        git rm    InformationInTransit/bin/Debug/InformationInTransit.Release2017-04-01T0919dll
        git rm    InformationInTransit/bin/Debug/InformationInTransit.dll
        git rm    InformationInTransit/bin/Debug/InformationInTransit.dll.config
        git rm    InformationInTransit/bin/Debug/MSOUTL.dll
        git rm    InformationInTransit/bin/Debug/Microsoft.SqlServer.Types.dll
        git rm    InformationInTransit/bin/Debug/MongoDB.Bson.dll
        git rm    InformationInTransit/bin/Debug/MongoDB.Bson.pdb
        git rm    InformationInTransit/bin/Debug/MongoDB.Driver.Core.dll
        git rm    InformationInTransit/bin/Debug/MongoDB.Driver.Core.pdb
        git rm    InformationInTransit/bin/Debug/MongoDB.Driver.GridFS.dll
        git rm    InformationInTransit/bin/Debug/MongoDB.Driver.GridFS.pdb
        git rm    InformationInTransit/bin/Debug/MongoDB.Driver.Legacy.dll
        git rm    InformationInTransit/bin/Debug/MongoDB.Driver.Legacy.pdb
        git rm    InformationInTransit/bin/Debug/MongoDB.Driver.dll
        git rm    InformationInTransit/bin/Debug/MongoDB.Driver.pdb
        git rm    InformationInTransit/bin/Debug/Newtonsoft.Json.dll
        git rm    InformationInTransit/bin/Debug/Newtonsoft.Json.pdb
        git rm    InformationInTransit/bin/Debug/Newtonsoft.Json.xml
        git rm    InformationInTransit/bin/Debug/System.Management.Automation.dll
        git rm    InformationInTransit/bin/Debug/System.Speech.dll
        git rm    InformationInTransit/bin/Debug/iTextSharp.dll

git add IIS/WordEngineering/JavaScript/htmldom.dev/
git add GitHub.com/2022-03-07T2029GitHub.bat