git add IIS/WordEngineering/WordUnion/BibleBook.aspx.cs
git add IIS/WordEngineering/WordUnion/BibleBook.xml
git add IIS/WordEngineering/WordUnion/BibleBook.xslt
git add IIS/WordEngineering/WordUnion/BibleBookRelease2014-10-09.xslt
git add IIS/WordEngineering/WordUnion/BibleWord.aspx.cs
git add IIS/WordEngineering/WordUnion/BiblicalCalendar.aspx.cs
git add IIS/WordEngineering/WordUnion/Carlos.aspx.cs
git add IIS/WordEngineering/WordUnion/DateAdd.aspx.cs
git add IIS/WordEngineering/WordUnion/DateApart.aspx.cs
git add IIS/WordEngineering/WordUnion/DateCompute.aspx.cs
git add IIS/WordEngineering/WordUnion/DateDifference.aspx.cs
git add IIS/WordEngineering/WordUnion/EsvApi.org.aspx.cs
git add IIS/WordEngineering/WordUnion/EternalBibleBook.bat
git add IIS/WordEngineering/WordUnion/FreeTextSearch.aspx.cs
git add IIS/WordEngineering/WordUnion/GrowingWithSchool.cs
git add IIS/WordEngineering/WordUnion/GrowingWithSchoolBuild.bat
git add IIS/WordEngineering/WordUnion/HisWord.aspx.cs
git add IIS/WordEngineering/WordUnion/Holiday.aspx.cs
git add IIS/WordEngineering/WordUnion/InSeldomWeekInComputerTermsWhatIsItCalled.aspx.cs
git add IIS/WordEngineering/WordUnion/MeetMyEndThrough.aspx.cs
git add IIS/WordEngineering/WordUnion/MyWord.aspx.cs
git add IIS/WordEngineering/WordUnion/Newtonsoft.Json.xml
git add IIS/WordEngineering/WordUnion/NotOnlyMeIWillBeAsSome.aspx.cs
git add IIS/WordEngineering/WordUnion/PhrasesInTheBible.aspx.cs
git add IIS/WordEngineering/WordUnion/RelatedVerses.aspx.cs
git add IIS/WordEngineering/WordUnion/ScriptureReference.aspx.cs
git add IIS/WordEngineering/WordUnion/ToCarrySomeone.Release2018-05-16T0811aspx.cs
git add IIS/WordEngineering/WordUnion/ToCarrySomeone.aspx.cs
git add IIS/WordEngineering/WordUnion/ToCarrySomeoneRelease2018-05-16T0724.aspx.cs
git add IIS/WordEngineering/WordUnion/ToCarrySomeoneRelease2018-05-16T0731.aspx.cs
git add IIS/WordEngineering/WordUnion/ToCarrySomeoneRelease2018-05-16T0823.aspx.cs
git add IIS/WordEngineering/WordUnion/ToCarrySomeoneRelease2018-05-16T0840.aspx.cs
git add IIS/WordEngineering/WordUnion/ToCarrySomeoneRelease2018-05-16T0905.aspx.cs
git add IIS/WordEngineering/WordUnion/ToMostExtentOfTalent.aspx.cs
git add IIS/WordEngineering/WordUnion/UnlessOneIsTrueWhereIsTheFound.aspx.cs
git add IIS/WordEngineering/WordUnion/WhereIHaveTrainedWhereIHaveFollowedToQueryAsSum.aspx.cs
git add IIS/WordEngineering/WordUnion/WordEntrance.aspx.cs
git add IIS/WordEngineering/WordUnion/WordsInTheBible.aspx.cs
git add IIS/WordEngineering/WordUnion/YouAreThePlaces.cs
git add IIS/WordEngineering/WordUnion/YouAreThePlacesBuild.bat
git add IIS/WordEngineering/WordUnion/nodeStartup.bat