<%@ Page Language="C#" AutoEventWireup="true" CodeFile="GeoNames.aspx.cs" Inherits="WebServiceRequester_GeoNames" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>GeoNames</title>
</head>
<body>
    <form id="form1" runat="server">
        <table align="center">
            <tr>
                <td>
                    <asp:Label
                        id="labelWebService"
                        runat="server" 
                        AssociatedControlID="webService"
                        Text="Web Service"
                    />            
                </td>
                <td>
                    <asp:DropDownList
                        id="webService"
                        runat="server"
                        DataTextField="Value"
                        DataValueField="Key" 
                    />            
                </td>
            </tr>
            <tr>                                
                <td>
                    <asp:Label
                        id="labelQ"
                        runat="server" 
                        AssociatedControlID="q"
                        Text="Q"
                    />            
                </td>
                <td>
                    <asp:TextBox
                        id="q"
                        runat="server"
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        id="labelName"
                        runat="server" 
                        AssociatedControlID="name"
                        Text="Name"
                    />            
                </td>
                <td>
                    <asp:TextBox
                        id="name"
                        runat="server"
                    />            
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        id="labelMaximumRows"
                        runat="server" 
                        AssociatedControlID="maximumRows"
                        Text="Maximum Rows"
                    />            
                </td>
                <td>
                    <asp:TextBox
                        id="maximumRows"
                        runat="server"
                        Text="100"
                    />
                    (The maximal allowed value is 1000)
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        id="labelStartRow"
                        runat="server" 
                        AssociatedControlID="startRow"
                        Text="Start Row"
                    />
                </td>
                <td>
                    <asp:TextBox
                        id="startRow"
                        runat="server"
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        id="labelCountry"
                        runat="server" 
                        AssociatedControlID="country"
                        Text="Country"
                    />            
                </td>
                <td>
                    <asp:TextBox
                        id="country"
                        runat="server"
                    />
                    ISO-3166.
                    (Separate using comma or semicolon)
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        id="labelGeonameId"
                        runat="server" 
                        AssociatedControlID="geonameId"
                        Text="GeonameId"
                    />            
                </td>
                <td>
                    <asp:TextBox
                        id="geonameId"
                        runat="server"
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        id="labelNorth"
                        runat="server" 
                        AssociatedControlID="north"
                        Text="North"
                    />            
                </td>
                <td>
                    <asp:TextBox
                        id="north"
                        runat="server"
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        id="labelSouth"
                        runat="server" 
                        AssociatedControlID="south"
                        Text="South"
                    />            
                </td>
                <td>
                    <asp:TextBox
                        id="south"
                        runat="server"
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        id="labelEast"
                        runat="server" 
                        AssociatedControlID="east"
                        Text="East"
                    />            
                </td>
                <td>
                    <asp:TextBox
                        id="east"
                        runat="server"
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        id="labelWest"
                        runat="server" 
                        AssociatedControlID="west"
                        Text="West"
                    />            
                </td>
                <td>
                    <asp:TextBox
                        id="west"
                        runat="server"
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        id="labelLatitude"
                        runat="server" 
                        AssociatedControlID="latitude"
                        Text="Latitude"
                    />            
                </td>
                <td>
                    <asp:TextBox
                        id="latitude"
                        runat="server"
                    />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label
                        id="labelLongitude"
                        runat="server" 
                        AssociatedControlID="longitude"
                        Text="Longitude"
                    />            
                </td>
                <td>
                    <asp:TextBox
                        id="longitude"
                        runat="server"
                    />
                </td>
            </tr>
            <tr>
                <td align="center" colspan="2">
                    <asp:Button
                        ID="QuerySubmit"
                        runat="server"
                        Text="Query Submit"
                        OnClick="QuerySubmit_Click"
                    />
                    <input
                        id="clear"
                        onclick="document.forms[0].reset();" 
                        type="button"
                        value="Reset"
                    />    
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <asp:HyperLink
                        id="webServiceUri"
                        runat="server" 
                        Target="_blank"
                    />
                </td>
            </tr>
        </table>
            
        <div align="center">
            <asp:GridView
                ID="gridViewGeoNames"
                runat="server"
            />
        </div>            
    </form>
</body>
</html>
