//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SoughtOutModel", "FK_Days_Actors", "Actors", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SoughtOutModel.Actors), "Days", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SoughtOutModel.Days), true)]

#endregion

namespace SoughtOutModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SoughtOutEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SoughtOutEntities object using the connection string found in the 'SoughtOutEntities' section of the application configuration file.
        /// </summary>
        public SoughtOutEntities() : base("name=SoughtOutEntities", "SoughtOutEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SoughtOutEntities object.
        /// </summary>
        public SoughtOutEntities(string connectionString) : base(connectionString, "SoughtOutEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SoughtOutEntities object.
        /// </summary>
        public SoughtOutEntities(EntityConnection connection) : base(connection, "SoughtOutEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Actors> Actors
        {
            get
            {
                if ((_Actors == null))
                {
                    _Actors = base.CreateObjectSet<Actors>("Actors");
                }
                return _Actors;
            }
        }
        private ObjectSet<Actors> _Actors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Days> Days
        {
            get
            {
                if ((_Days == null))
                {
                    _Days = base.CreateObjectSet<Days>("Days");
                }
                return _Days;
            }
        }
        private ObjectSet<Days> _Days;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Actors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActors(Actors actors)
        {
            base.AddObject("Actors", actors);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Days EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDays(Days days)
        {
            base.AddObject("Days", days);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoughtOutModel", Name="Actors")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Actors : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Actors object.
        /// </summary>
        /// <param name="actorID">Initial value of the ActorID property.</param>
        /// <param name="dated">Initial value of the Dated property.</param>
        public static Actors CreateActors(global::System.Int32 actorID, global::System.DateTime dated)
        {
            Actors actors = new Actors();
            actors.ActorID = actorID;
            actors.Dated = dated;
            return actors;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActorID
        {
            get
            {
                return _ActorID;
            }
            set
            {
                if (_ActorID != value)
                {
                    OnActorIDChanging(value);
                    ReportPropertyChanging("ActorID");
                    _ActorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActorID");
                    OnActorIDChanged();
                }
            }
        }
        private global::System.Int32 _ActorID;
        partial void OnActorIDChanging(global::System.Int32 value);
        partial void OnActorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Dated
        {
            get
            {
                return _Dated;
            }
            set
            {
                OnDatedChanging(value);
                ReportPropertyChanging("Dated");
                _Dated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dated");
                OnDatedChanged();
            }
        }
        private global::System.DateTime _Dated;
        partial void OnDatedChanging(global::System.DateTime value);
        partial void OnDatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ScriptureReference
        {
            get
            {
                return _ScriptureReference;
            }
            set
            {
                OnScriptureReferenceChanging(value);
                ReportPropertyChanging("ScriptureReference");
                _ScriptureReference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ScriptureReference");
                OnScriptureReferenceChanged();
            }
        }
        private global::System.String _ScriptureReference;
        partial void OnScriptureReferenceChanging(global::System.String value);
        partial void OnScriptureReferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Commentary
        {
            get
            {
                return _Commentary;
            }
            set
            {
                OnCommentaryChanging(value);
                ReportPropertyChanging("Commentary");
                _Commentary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Commentary");
                OnCommentaryChanged();
            }
        }
        private global::System.String _Commentary;
        partial void OnCommentaryChanging(global::System.String value);
        partial void OnCommentaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Uri
        {
            get
            {
                return _Uri;
            }
            set
            {
                OnUriChanging(value);
                ReportPropertyChanging("Uri");
                _Uri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Uri");
                OnUriChanged();
            }
        }
        private global::System.String _Uri;
        partial void OnUriChanging(global::System.String value);
        partial void OnUriChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SoughtOutModel", "FK_Days_Actors", "Days")]
        public EntityCollection<Days> Days
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Days>("SoughtOutModel.FK_Days_Actors", "Days");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Days>("SoughtOutModel.FK_Days_Actors", "Days", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SoughtOutModel", Name="Days")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Days : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Days object.
        /// </summary>
        /// <param name="dayID">Initial value of the DayID property.</param>
        /// <param name="dated">Initial value of the Dated property.</param>
        public static Days CreateDays(global::System.Int32 dayID, global::System.DateTime dated)
        {
            Days days = new Days();
            days.DayID = dayID;
            days.Dated = dated;
            return days;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DayID
        {
            get
            {
                return _DayID;
            }
            set
            {
                if (_DayID != value)
                {
                    OnDayIDChanging(value);
                    ReportPropertyChanging("DayID");
                    _DayID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DayID");
                    OnDayIDChanged();
                }
            }
        }
        private global::System.Int32 _DayID;
        partial void OnDayIDChanging(global::System.Int32 value);
        partial void OnDayIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Dated
        {
            get
            {
                return _Dated;
            }
            set
            {
                OnDatedChanging(value);
                ReportPropertyChanging("Dated");
                _Dated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dated");
                OnDatedChanged();
            }
        }
        private global::System.DateTime _Dated;
        partial void OnDatedChanging(global::System.DateTime value);
        partial void OnDatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ActorID
        {
            get
            {
                return _ActorID;
            }
            set
            {
                OnActorIDChanging(value);
                ReportPropertyChanging("ActorID");
                _ActorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActorID");
                OnActorIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ActorID;
        partial void OnActorIDChanging(Nullable<global::System.Int32> value);
        partial void OnActorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ScriptureReference
        {
            get
            {
                return _ScriptureReference;
            }
            set
            {
                OnScriptureReferenceChanging(value);
                ReportPropertyChanging("ScriptureReference");
                _ScriptureReference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ScriptureReference");
                OnScriptureReferenceChanged();
            }
        }
        private global::System.String _ScriptureReference;
        partial void OnScriptureReferenceChanging(global::System.String value);
        partial void OnScriptureReferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Commentary
        {
            get
            {
                return _Commentary;
            }
            set
            {
                OnCommentaryChanging(value);
                ReportPropertyChanging("Commentary");
                _Commentary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Commentary");
                OnCommentaryChanged();
            }
        }
        private global::System.String _Commentary;
        partial void OnCommentaryChanging(global::System.String value);
        partial void OnCommentaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Uri
        {
            get
            {
                return _Uri;
            }
            set
            {
                OnUriChanging(value);
                ReportPropertyChanging("Uri");
                _Uri = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Uri");
                OnUriChanged();
            }
        }
        private global::System.String _Uri;
        partial void OnUriChanging(global::System.String value);
        partial void OnUriChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SoughtOutModel", "FK_Days_Actors", "Actors")]
        public Actors Actors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actors>("SoughtOutModel.FK_Days_Actors", "Actors").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actors>("SoughtOutModel.FK_Days_Actors", "Actors").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Actors> ActorsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Actors>("SoughtOutModel.FK_Days_Actors", "Actors");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Actors>("SoughtOutModel.FK_Days_Actors", "Actors", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
